<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();	
$newsLetterblock= $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe'); 
?>
<div class="mb-block-newsletter mb-block" data-bind="scope: 'newsletter'">
    <div class="block-title"><strong><?= $newsLetterblock->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $newsLetterblock->escapeUrl($newsLetterblock->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $newsLetterblock->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                                placeholder="<?= $newsLetterblock->escapeHtml(__('Enter your email address')) ?>"
                                data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="subscribe" title="<?= $newsLetterblock->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" aria-label="Subscribe">
                    <span class="icon"><svg xmlns="https://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg></span>
                    <span class="text"><?= $newsLetterblock->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
</div>



