<?php 
if($block->getLayer()->getProductCollection()->getSize()): 
	$topFilterBlock=$this->getLayout()->getBlock('catalog.leftnav1');
	$sideFilters=$topFilterBlock->getSidebarFilters($block->getFilters());
	$helper=$this->helper('\Magebees\Layerednavigation\Helper\Data');	
    $generalConfig=$helper->getGeneralConfigData();	
	
	$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
	$storeId = $poco_helper->getStoreId();
	$page_layout = $poco_helper->getProductListing('page_layout',$storeId);

?>
	<?php if ($block->canShowBlock()): ?>
		<div class="block filter <?php if($page_layout == '1column'){ echo 'hrl_filter'; } ?>" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
			<?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
	        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
	            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
	        </div>
	        <div class="block-content filter-content">
	        	<?php echo $block->getChildHtml('state') ?>
	        	<?php if ($block->getLayer()->getState()->getFilters()): ?>
	                <div class="block-actions filter-actions">
	                    <a href="<?php echo $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
	                </div>
            	<?php endif; ?>
            	<?php $wrapOptions = false; ?>
            	<?php foreach ($sideFilters as $filter): ?>
            		<?php if(($filter->hasAttributeModel())&&($filter->getAttributeModel()->getFrontendInput()=='boolean')): ?>
						<?php $include_filter=false; ?>
					<?php else: ?>
						<?php $include_filter=true; ?>
					<?php endif; ?>
					<?php if($include_filter): ?>
					<?php 
						$shuffle_name=str_shuffle($filter->getName());
						$shuffle_code = preg_replace('/[^a-zA-Z0-9]/s', '',$shuffle_name);
						$is_applied=$topFilterBlock->checkAppliedFilter($filter->getRequestVar());
						if($filter->hasAttributeModel())	
						{
							$attr_id=$filter->getAttributeModel()->getId();
							$include_cat=$helper->getIncludeCategories($attr_id);
							$exclude_cat=$helper->getExcludeCategories($attr_id);
							$tooltip=$helper->getTooltip($attr_id);
							
							if($filter instanceof \Magento\CatalogSearch\Model\Layer\Filter\Price ){	
								$priceConfig=$helper->getPriceConfigData();
								$collapse_filter=$priceConfig['collapse_price'];				
							
							} else {
								$collapse_filter=$helper->checkCollapseFilter($attr_id);
								
							}
						} else if($filter instanceof \Magebees\Layerednavigation\Model\Layer\Filter\Rating) {
							$ratingConfig=$helper->getRatingConfigData();
							$collapse_filter=$ratingConfig['collapse_rating'];				
							$tooltip="";
						} else if($filter instanceof \Magebees\Layerednavigation\Model\Layer\Filter\Stock) {
							$stockConfig=$helper->getStockConfigData();
							$collapse_filter=$stockConfig['collapse_stock'];				
							$tooltip="";
						} else if($filter instanceof \Magebees\Layerednavigation\Model\Layer\Filter\Category) {
							$catConfig=$helper->getCatConfigData();
							$collapse_filter=$catConfig['collapse_cat'];
							$tooltip="";
						}						
						if(!isset($include_cat)){
							$include_cat=1;
						}
						if(!isset($exclude_cat)){
							$exclude_cat=0;
						}
					?>
						<?php if ($filter->getItemsCount()): ?>
							<?php 	$layer_collapse=$generalConfig['layer_collapse']; ?>
							<?php if (!$wrapOptions): ?>
                        		<strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                        		<div class="filter-options" id="narrow-by-list_<?php echo $shuffle_code;?>" data-role="content">
                    		<?php  $wrapOptions = true; ?>
                    		<?php endif; ?>
                    		<?php if($exclude_cat==0): ?>
								<?php if($include_cat==1): ?>
									<div data-role="collapsible" class="filter-options-item">
										<div data-role="title" id="filter-options-title_<?php
echo $shuffle_code;
?>" data-layercollapse='<?php echo $layer_collapse;?>' class="filter-options-title <?php
if (isset($collapse_filter)) {
    if ($collapse_filter == 0) { ?>active <?php  } }
if ($layer_collapse) { ?>collapsible<?php } ?>" data-filter="<?php echo $filter->getName(); ?>">
                                           <?php echo __($filter->getName()); ?>
                                           <?php $tooltip_image_url = $block->getViewFileUrl('Magebees_Layerednavigation::images/tooltip.png');
if ($tooltip) { ?>
                                               <img src="<?php echo $tooltip_image_url; ?>" title="<?php echo $tooltip; ?>" class="tooltip" />
                                            <?php } ?>
                                       </div>							
										
										<div data-role="content" id="filter-options-content_<?php echo $shuffle_code;?>" class="filter-options-content" <?php 
											if($layer_collapse){
												if(isset($collapse_filter)){  
													if($collapse_filter==1){ ?>
													style="display:none;" <?php }}}?> >
													<?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>
				                   		</div>
									</div>
								<?php endif; ?>		
							<?php endif; ?>	
						<?php endif; ?>
					<?php endif; ?>
			   	<?php endforeach; ?>
			   	 <?php if ($wrapOptions): ?>
			   	 </div>
			   	<?php endif;?>
	        </div>
		</div>
	<?php endif; ?>
	<?php 
	$verticalScrolling=$generalConfig['vertical_scroll'];
	if($verticalScrolling): ?>
	<style>	
		.filter-options-content {
	   		max-height: <?php echo $verticalScrolling.'px' ?>;   		
	   		overflow-x: hidden;
		}
	</style>
	<?php endif; ?>
<?php endif; ?>