<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

?>
<?php 

$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_poco_helper = $_objectManager->get('Magebees\PocoThemes\Helper\Data');
$loaderUrl = $_poco_helper->getLoadingIcon(); 
	
 ?>

<div data-role="main-css-loader" class="loading-mask">
    <div class="loader">
        <img loading="lazy" src="<?= $escaper->escapeUrl($loaderUrl); ?>"
             alt="<?= $escaper->escapeHtml(__('Loading...')); ?>" width="90" height="90" >
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "position: absolute;",
        "div.loader img"
    ) ?>
</div>
