<?php if($block->getFilterval()==$block->getStar()){?><span style='background-color:#e8e8e8;'><?php }?>
<div class="rating-summary" style="display: inline-block;margin-top: -5px;">
    <div class="rating-result" title="<?php echo ($block->getStar()*20);?>%">
        <span style="width:<?php echo ($block->getStar()*20);?>%"><span><?php echo $block->getStar(); //($block->getStar()*20).'%';?></span></span>
    </div>
</div>
<?php if($block->getStar() != 5):?>
    <span style="font-size: smaller;">&amp; <?php /* @escapeNotVerified */ echo __('up'); ?></span>
<?php endif; ?>
<?php if($block->getFilterval()==$block->getStar()){?></span><?php }?>