<?php 
$randon_number = rand();	
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$adverticementWidgetData = $this->getData();
if(count($adverticementWidgetData)>0):
$adverticementWidgetEmptyOptions = array('template'=>null,'wd_spacing'=>null,'wd_bottom_spacing'=>null,'wd_advertisement'=>null,'wd_style'=>null,'store_id'=>null,'enabled'=>null,'title'=>null,'subtitle'=>null,'advertisement'=>null,'style'=>null);
$adverticementWidget = array();
$ajaxLoadingData = array();
$ajaxLoadingData['randon_number'] = $randon_number;
$ajaxLoadingData['url'] = $block->getUrl('poco/index/advertisement');
$ajaxLoadingData['res_div'] = '#adverticement'.$randon_number;
$ajaxLoadingData['loading_div'] = '#loadingImage'.$randon_number;
$ajaxLoadingData['loaderUrl'] = $poco_helper->getLoadingIcon();  
$adverticementWidget['ajaxloading'] = (array_merge($adverticementWidgetEmptyOptions,$adverticementWidgetData,$ajaxLoadingData));
?>
<div id="adverticement<?php echo $randon_number; ?>" class="ajx_loader" data-mage-init='<?php echo  $poco_helper->getJsonEncode($adverticementWidget);?>'>
<div id="loadingImage<?php echo $randon_number; ?>" style="display:none;"></div>
</div>
<?php endif; ?>