<?php use Magento\Framework\App\Action\Action; ?>
<?php $poco_helper = $this->helper('Magebees\PoshThemesCakes\Helper\Data'); ?>
<?php 
	$bg_image = $poco_helper->getMediaUrl().$this->getData('wd_bgimage');
	$image_position = $this->getData('wd_position');
	$pos_class = ($image_position == "left") ? "parallax-img-left" : "parallax-img-right" ;
	$content_class = ($image_position == "left") ? "content-text-left" : "content-text-right" ;
	$text_class = ($image_position == "left") ? "parallax-text-left" : "parallax-text-right" ;

	$content_type = $this->getData('wd_content');
	$bg_color = $this->getData('wd_bgcolor');
	$title = $this->getData('wd_title');
	$subtitle = $this->getData('wd_subtitle');
	$description = $this->getData('wd_description');
	$shopnow_text = $this->getData('wd_shopnow_text');

	$spacing_class = '';
	$spacing_class .= $this->getData('wd_spacing')?'sections-spacing ':'';
	$spacing_class .= $this->getData('wd_bottom_spacing')?'section-bottom-spacing':'';

	$shopnow_url = $poco_helper->getUrl().$this->getData('wd_shopnow_url');
	$_productCollection = $block->getLoadedProductCollection();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<div class="parallax-section <?php echo $spacing_class ?>">
	<!-- Parallax Image -->
	<div class="half-col display-flex parallax-image <?php echo $pos_class ?>">
		<div class="zoom img_parallax" style="background-image: url('<?php echo $bg_image; ?>');"></div>
	</div>
	<!-- End Parallax Image -->
	
	<!-- Parallax Content -->
	<div class="half-col display-flex product-section feature-row__text <?php echo $content_class; ?>"  style="background-image: url('<?php echo $bg_image; ?>'); background-color: <?php echo $bg_color ?>; background-repeat: no-repeat;">
		<div class="parallax-product <?php echo $text_class ?>">
			<div class="feature-details">
				<?php if ($content_type == "desc"): ?>
					<div class="section-title">
						<h2 class="title"><?php echo __($title) ?></h2>
						<h3 class="section-subtitle"><?php echo __($subtitle) ?></h3>
						<p><?php echo $description ?></p>
						<a href="<?php echo $shopnow_url ?>" class="btn button"><span><?php echo __($shopnow_text) ?></span></a> 
					</div>
				<?php else: ?>
					<?php if (!$_productCollection->count()): ?>
						<div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
					<?php else: ?>
						<?php
							$viewMode = 'grid';
							$image = 'category_page_grid';
							$showDescription = false;
							$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

							/**
							 * Position for actions regarding image size changing in vde if needed
							 */
							$pos = $block->getPositioned();
							$position = '';
							if ($pos != null) {
								$position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
										. 'top:' . $block->getVar("{$image}:height") . 'px;"';
							}
						?>
						<div class="<?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
							<div class="section-title">
								<h2 class="title"><?php echo __($title) ?></h2>
								<h3 class="section-subtitle"><?php echo __($subtitle) ?></h3>
							</div>
							<?php $iterator = 1; ?>
							<ol class="products list items product-items">
							  <?php foreach ($_productCollection as $_product): ?>
									<?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
									<div class="product-item-info" data-container="product-grid">
										<div class="pro-hover">
											<?php // Product Image   ?>
											<?php $productImage = $block->getImage($_product, $image); ?>
											<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
												<?php echo $productImage->toHtml(); ?>
											</a>
											
											<?php echo $this->getLayout()->createBlock('Magebees\PoshThemesFashion\Block\AddToButtons')->setProduct($_product)->toHtml(); ?>
										</div>
									   	<div class="product details product-item-details">
										  	<?php echo $block->getProductDetailsHtml($_product); ?>
											<?php
											$_productNameStripped = $block->stripTags($_product->getName(), null, true);
											?>
											<strong class="product name product-item-name">
												<a class="product-item-link"
												   href="<?php echo $_product->getProductUrl() ?>">
													   <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
												</a>
											</strong>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
											<?php echo $block->getProductPrice($_product) ?>
										</div>
									</div>
									<?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
								<?php endforeach; ?>
							</ol>
							<div class="view-more">
								<a href="<?php echo $shopnow_url ?>" class="btn button"><span><?php echo __($shopnow_text) ?></span></a> 
							</div>
						</div>
						<?php if (!$block->isRedirectToCartEnabled()) : ?>
							<script type="text/x-magento-init">
								{
									"[data-role=tocart-form], .form.map.checkout": {
										"catalogAddToCart": {}
									}
								}
							</script>
						<?php endif; ?>
					<?php endif; ?>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<!-- End Parallax Content --> 
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "parallax": {}
        }
    }
</script>