<?php $mail_helper = $this->helper('Magebees\EmailEditor\Helper\Data');

$image=$mail_helper->getDarkLogoImageUrl();
$alt_text=$mail_helper->getConfig('emaileditor/dark_logo/alt_text');
$width=$mail_helper->getConfig('emaileditor/dark_logo/width');
$height=$mail_helper->getConfig('emaileditor/dark_logo/height');
$link=$mail_helper->getConfig('emaileditor/dark_logo/link');
?>
<?php if($image): ?>
 <a href="<?= $link ?>"><img height="<?= $height ?>" width="<?= $width ?>" src="<?= $image ?>" alt="<?= $alt_text ?>"/></a>
 <?php endif;?>