<ul>
	<li><a href="https://www.facebook.com/" target="_blank"><img title="Facebook" src="images/facebook.png"" width="30" height="30" /></a></li>
	<li><a href="https://twitter.com/" target="_blank"><img title="Twitter" src="images/twitter.png"" width="30" height="30" /></a></li>
	<li><a href="https://plus.google.com/" target="_blank"><img title="Google Plus" src="images/google-plus.png"" width="30" height="30" /></a></li>
	<li><a href="https://in.linkedin.com/" target="_blank"><img title="Instagram" src="images/instagram.png"" width="30" height="30" /></a></li>
</ul>