<?php
    $poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$enable = (bool)$poco_helper->getProductDetail('prev_next',$poco_helper->getStoreId()); 
	
	if($enable) {
		$_product = $block->getProduct();
        $prev_product = $poco_helper->getPrevProduct($_product);
		$next_product = $poco_helper->getNextProduct($_product);
?>

<?php if($prev_product || $next_product):?>
<div class="prev-next-products">
    <?php if($prev_product): ?>
    <?php
        $productImage = $_imagehelper->init($prev_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(80);
        $productImageUrl = $productImage->getUrl();
    ?>
	<div class="prev-product">
		<a href="<?php echo $prev_product->getProductUrl(); ?>" title="<?php echo __('Previous Product'); ?>">
			<?php echo $poco_helper->getProductDetail('prev_text',$poco_helper->getStoreId()) ?>
		</a>
		<div class="pn-product-detail hidden-s">
			<img class="product-image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>" title="<?php echo $productImage->getLabel(); ?>" width="80" height="97"/>
			<h3 class="product-name"><?php echo $prev_product->getName(); ?></h3>
			<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
		</div>
	</div>
    <?php endif; ?>
    <?php if($next_product): ?>
    <?php
        $productImage = $_imagehelper->init($next_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(80);
        $productImageUrl = $productImage->getUrl();
    ?>
    
	<div class="next-product">
		<a href="<?php echo $next_product->getProductUrl(); ?>" title="<?php echo __('Next Product'); ?>" class="next-arrw">
			<?php echo $poco_helper->getProductDetail('next_text',$poco_helper->getStoreId()) ?>
		</a>
		<div class="pn-product-detail hidden-s">
			<img class="product-image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>" title="<?php echo $productImage->getLabel(); ?>" width="80" height="97" />
			<h3 class="product-name"><?php echo $next_product->getName(); ?></h3>
			<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
		</div>
	</div>
    <?php endif; ?>
</div>
<?php endif; ?>
<?php
   }
?>