<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Model\Product;
use Magento\Swatches\Block\Product\Renderer\Listing\Configurable;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

/** @var Configurable $block */
/** @var Product $product */
$product = $block->getProduct()
?>
<?php if ($product && $product->isAvailable()): ?>
    <?php $productId = $product->getId() ?>
    <?php /** @var ConfigurableViewModel $configurableViewModel */ ?>
    <?php //$configurableViewModel = $block->getConfigurableViewModel(); ?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$configurableViewModel = $objectManager->create('Magento\Swatches\ViewModel\Product\Renderer\Configurable');
	
?>

	<?php 
	
	$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$enable_swatch = $poco_helper->getProductListing('enable_swatch',$poco_helper->getStoreId());
if($enable_swatch):
?><div class="swatches-listing">
    <div class="swatch-opt-<?= $block->escapeHtmlAttr($productId) ?>"
         data-role="swatch-option-<?= $block->escapeHtmlAttr($productId) ?>"></div>
</div>
    <script type="text/x-magento-init">
        {
            "[data-role=swatch-option-<?= $block->escapeJs($productId) ?>]": {
                "Magento_Swatches/js/swatch-renderer": {
                    "selectorProduct": ".product-item-details",
                    "onlySwatches": true,
                    "enableControlLabel": false,
                    "numberToShow": <?=  $block->escapeJs($block->getNumberSwatchesPerProduct()) ?>,
                    "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "jsonSwatchConfig": <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>,
                    "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                    "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                    "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
                }
            }
        }
    </script>

    <script type="text/x-magento-init">
        {
            "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeJs($productId) ?>]": {
                "priceBox": {
                    "priceConfig": {
                        "priceFormat": <?= /* @noEscape */ $block->getPriceFormatJson() ?>,
                        "prices": <?= /* @noEscape */ $block->getPricesJson() ?>
                    }
                }
            }
        }
    </script>
<?php endif; ?>
<?php endif; ?>
