<?php 
$is_enable=$block->getEnabled();
$title=$block->getTitle();
$sub_title=$block->getSubtitle();
$advertisement_id=$block->getAdvertisement();
$adv_style=$block->getStyle();
$helper=$this->helper('\Magebees\Advertisementblock\Helper\Data');	
$resizes_img_dir=$helper->getResizedImgDir();
$img_dir=$helper->getImageMediaDir();
$advertise_info=$helper->getAdvertiseBlockdetail($advertisement_id);
$pattern_div_arr       = array(
    '13',
    '14',
    '16',
    '17',
    '21',
    '26',
    '28'
);
$three_col_pattern_arr = array(
    '13',
    '14',
    '21',
    '26',
    '28'
);
$two_col_pattern_arr   = array(
    '16',
    '17'
);
$img_divarr=$helper->getPatternImgDiv();
$parentDivarr=$helper->getColumnParentDiv();
$patternImageSize=$helper->getPatternImageSize();
?>
<?php if (isset($advertise_info[0])): ?>
	<?php
	$adv_data = $advertise_info[0];
    $status   = $adv_data['status'];
    $pattern  = $adv_data['pattern'];
    ?>
	<?php if ($is_enable): ?>
		<?php if ($status): ?>
			<div class="maagebees-add">
				<?php if($title): ?>
					<div class="section-title">
						<h2 class="title"><?php echo $title; ?></h2>
					</div>
				<?php endif; ?>
				<?php if($sub_title): ?>
					<h5 class="section-subtitle"><?php echo $sub_title; ?></h5>
				<?php endif; ?>
				<div class="mageb-patn-inner">
					<?php
					if ($pattern == 1) {
						if ($adv_style == 1) {
							$style_class = 'full-width';
						} else {
							$style_class = 'boxed';
						}
					}
					?>
					<?php
					if (in_array($pattern, $pattern_div_arr)): ?>
						<?php if (in_array($pattern, $three_col_pattern_arr)) {
							$col_class = 'mageb-three-col';
						} else if (in_array($pattern, $two_col_pattern_arr)) {
							$col_class = 'mageb-two-col';
						} ?>
						<div class = "mageb-patterns mageb-<?php echo 'pattern'.$pattern;?> <?php echo $col_class; ?>" > 
					<?php else: ?>
						<ul class = "mageb-patterns mageb-<?php echo 'pattern'.$pattern;?> <?php if($pattern==1) { echo $style_class; } ?> ">
					<?php endif; ?>
					<?php $advertise_img_detail=$helper->getAdvertiseImagedetail($advertisement_id); ?>
					<?php if($advertise_img_detail): ?>
						<?php $i=-1; ?>
						<?php foreach($advertise_img_detail as $advertise): ?>
							<?php
							$i++;
							$show_hover_heading_text = $advertise['show_hover_heading_text'];
							$hover_heading_text = $advertise['hover_heading_text'];
							$show_hover_short_text = $advertise['show_hover_short_text'];
							$hover_short_text = $advertise['hover_short_text'];
							$show_button_text = $advertise['show_button_text'];
							$button_text = $advertise['button_text'];
							$text_position = $advertise['text_position'];

							$display_text_mode = $advertise['display_text_mode']; // on hover or page load

							$show_image = $advertise['show_image'];
							$bg_color = $advertise['bg_color'];

							$heading_text_color = $advertise['heading_text_color'];
							$heading_text_size = $advertise['heading_text_size'];

							$short_text_color = $advertise['short_text_color'];
							$short_text_size = $advertise['short_text_size'];

							$button_text_color = $advertise['button_text_color'];
							$button_bg_color = $advertise['button_bg_color'];
							$button_text_size = $advertise['button_text_size'];
							?>
							<?php if($pattern==1): ?>
								<?php
								if ($adv_style == 1) {
									$img_path = $img_dir.$advertise['filename'];
								} else {
									$img_path = $resizes_img_dir.$advertise['filename'];
								}
								?>
							<?php else: ?>
								 <?php $img_path=$resizes_img_dir.$advertise['filename']; ?>
							<?php endif; ?>
							<?php 
							$effect=$advertise['image_effect'];
							$img_url=$advertise['advertise_url'];
							?>
							<?php if (in_array($pattern,$pattern_div_arr)): ?>
								<?php 
								$img_classes=$img_divarr[$pattern];
								$parent_div=$parentDivarr[$pattern];
								for ($j = 0; $j < 3; $j++) {
									if (isset($parent_div[$j])) {
										$add_div_arr = explode(",", $parent_div[$j][0]);
										if ($i == current($add_div_arr)) { ?>
											<div class = "<?php echo $parent_div[$j][1];?>" >
								<?php
										}
									}
								}
								?>
								<div class="mageb-pattern-list mageb-<?php echo $effect;?>  <?php echo $img_classes[$i];?>">
							<?php else: ?>
								<li class="mageb-pattern-list mageb-<?php echo $effect;?>">
							<?php endif; ?>
									<div class="mageb-effects">
										<?php if(($show_image) &&($advertise['filename'])): ?>
											<a href="<?php echo $img_url;?>" target="_blank">
												<img src="<?php echo $img_path;?>" alt="<?php echo $hover_heading_text;?>" title="<?php echo $hover_heading_text;?>" />
											</a>											
										<?php else: ?>
											<?php if(!$bg_color) {
													$bg_color='#ffffff';
												}
												$img_dimension=$patternImageSize[$pattern][$i];
												$img_dim_arr=explode('*',$img_dimension);
											?>
											<div style="background-color:<?php echo $bg_color; ?>;height:<?php echo $img_dim_arr[1].'px'; ?>;width:<?php echo $img_dim_arr[0].'px'; ?>" title="<?php echo $hover_heading_text;?>"></div>
										<?php endif; ?>
									</div>
									<?php if(($show_hover_heading_text)||($show_hover_short_text)||($show_button_text)): ?>
										<div class="mageb-caption <?php echo($text_position=='0'? "v-top" : ($text_position=='1'? "v-middle" : ($text_position=='2' ? "v-bottom" : "unknown")));?>
								<?php echo($display_text_mode=='0'? "mageb-on-hover-caption" : ($display_text_mode=='1'? "mageb-on-load-caption" : "unknown"));?>">
									<div class="mageb-full-caption">
										<h4 style="color:<?php echo $heading_text_color; ?>; font-size:<?php echo $heading_text_size; ?>"><?php echo $hover_heading_text; ?></h4>
										<div class="sort-text" style="color:<?php echo $short_text_color; ?>; font-size:<?php echo $short_text_size; ?>"><?php echo __($hover_short_text); ?></div>
										<?php if(($show_button_text)&&($button_text)): ?>
													<a title="<?php echo $button_text;?>" href="<?php echo $img_url;?>" class="button" target="_blank"
														style="color:<?php echo $button_text_color; ?>; font-size:<?php echo $button_text_size; ?>; background-color:<?php echo $button_bg_color; ?>;">
														<?php echo $button_text; ?>
													</a>
												<?php endif; ?>
											</div>
										</div>
									<?php endif; ?>
							<?php if (in_array($pattern,$pattern_div_arr)): ?>
								</div>
								<?php $parent_div=$parentDivarr[$pattern];
								for($j=0;$j<3;$j++){
									if(isset($parent_div[$j])){
										$add_div_arr=explode(",",$parent_div[$j][0]);	
										if($i==end($add_div_arr)){ ?>
									</div>
										<?php }
									} 
								} ?>
							<?php else: ?>
								</li>
							<?php endif; ?>
						<?php endforeach; ?>
						<?php if (in_array($pattern,$pattern_div_arr)): ?>
							</div>
						<?php else: ?>
							</ul>
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>