<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$helper = $this->helper('Magebees\Ajaxquickview\Helper\Data');
$mage_version = $helper->getMagentoVersion();
	
if(version_compare($mage_version, '2.3.0', '>'))
{
$block=$this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Details');
$detailedInfoGroup=$block->getGroupSortedChildNames('detailed_info', 'getChildHtml');
$arialabeledby='aria-labelledby';
}
else
{
	$detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml');
	$arialabeledby='aria-labeledby';
}
if ($detailedInfoGroup):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title" <?php if(version_compare($mage_version, '2.3.0', '>')):?>
                     aria-labelledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
					 <?php else:?>
					   aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
					  <?php endif;?>
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
