<?php
/**
 * Subcategory image template
 *
 * @var $block \Magebees\CategoryImage\Block\Image
 */
?>
<?php

$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$storeId = $poco_helper->getStoreId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);

$_helper = $this->helper('Magebees\CategoryImage\Helper\Category');
$rootCatId = $storeManager->getStore($storeId)->getRootCategoryId();
$RootCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($rootCatId);
$current_cat_id = $RootCategory->getId();
$category_all_childs =  $RootCategory->getAllChildren(true);
if(isset($category_all_childs[0]))
{
	if($category_all_childs[0] == $current_cat_id)
	{
		unset($category_all_childs[0]);
	}
}
?>
<?php if(count($category_all_childs)>0):

$ItemClass = 'item';
$rtl = $poco_helper->getThemeLayout('rtl',$poco_helper->getStoreId())? true:false; 
$animation = $poco_helper->getThemeLayout('animation',$poco_helper->getStoreId())? true:false; 
$animation_class = $animation?"wow animate__fadeIn":" ";
$_categoryModel = $objectManager->create('Magento\Catalog\Model\CategoryFactory');
?>

<div class="sct_grid d-flex align-item-start">
<?php
    foreach ($category_all_childs as $key => $catId) {
           $_category = $_categoryModel->create()->load($catId);
          if(($_category->getId())&&($_category->getIsActive())):
			$subcaturl = $_category->getUrl();
			$_imgHtml = '';
            if ($_imgUrl = $_category->getThumbnail()) 	{
				$_imgUrl = $_helper->getThumbnailImageUrl($_category);
            } else {
				$_imgUrl = $block->getViewFileUrl('images/Image_not_available.png');
			}
			if(($_category->getShowProductCounter())&&($_category->getShowProductCounter()!="0")&&($_category->getProductCount()>0)){
				
					$align_class = 'justify-space-between';
				}else{
					$align_class = 'justify-content-center';
				}
				
			?>
			<div class="<?php echo $ItemClass; ?>">	
			<div class="thumb">	
			<a href="<?php echo $subcaturl; ?>" class="img" title="<?php echo $_category->getName(); ?>">
			<img src="<?php echo $_imgUrl; ?>" alt="<?php echo $_category->getName(); ?>" title="<?php echo $_category->getName(); ?>" />';
			</a>
			</div>
			<div class="ct_dtl">
						<div class="d-flex <?php echo $align_class;?>">
						<a href="<?php echo $subcaturl; ?>" class="ttl" title="<?php echo $_category->getName(); ?>">
							<span><?php echo $_category->getName(); ?></span></a>
							<?php if(($_category->getShowProductCounter())&&($_category->getShowProductCounter()!="0")&&($_category->getProductCount()>0)): ?>
							<div class="ctr_prd"><?php echo $_category->getProductCount(); ?> + <span>Items</span></div>
							<?php endif;?>
						</div>
					</div>
			</div>
				<?php
            
           endif;
	} 
	?>
</div>
<?php endif; ?>