<?php
/**
 * Subcategory image template
 *
 * @var $block \Magebees\CategoryImage\Block\Image
 */
?>
<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $block->getCurrentCategory();//get current category
$current_cat_id = $category->getId();
$category_all_childs =  $category->getAllChildren(true);
if(isset($category_all_childs[0]))
{
	if($category_all_childs[0] == $current_cat_id)
	{
		unset($category_all_childs[0]);
	}
}

$_helper = $this->helper('Magebees\CategoryImage\Helper\Category');
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$storeId = $poco_helper->getStoreId();
$storeId = $poco_helper->getStoreId(); 
$pubPath = $poco_helper->getPubAbsolutePath();

$enable = $poco_helper->getProductListing('enable_subcategory_thumbnail',$storeId);
$no_of_items_per_slider = $poco_helper->getProductListing('no_of_items_per_slide',$storeId);
$items_per_slider = $no_of_items_per_slider ? $no_of_items_per_slider:4;
$mediaURL = $poco_helper->getStoreMediaUrl($storeId);		

?>
<?php if(($enable)&&(count($category_all_childs)>0)):
$random_number = rand();
$slider_id= 'subcategory-grid-'.$random_number;
$no_of_items = count($category_all_childs);
$sliderClass= 'swiper swiper-container';
$sliderWarperClass= 'swiper-wrapper';
$sliderItemClass = 'swiper-slide';

 $swiper_data_init = array();
		$swiper_data_init['slider_id'] = $slider_id;
		$swiper_data_init['autoHeight'] = false;
		$swiper_data_init['slidesPerView'] = 1;
		$swiper_data_init['spaceBetween'] = 10;
		$swiper_data_init['lazy']['loadPrevNext'] = true;
		$swiper_data_init['lazy']['loadPrevNextAmount'] = $no_of_items;
		$swiper_data_init['a11y'] = false;
		$swiper_data_init['speed'] = 600;
		$swiper_data_init['loop'] = false;
		$swiper_data_init['grabCursor'] = true;
		$swiper_data_init['centeredSlides'] = false;
		 
		$swiper_data_init['autoplay']['delay'] = 6000;
		$swiper_data_init['autoplay']['disableOnInteraction'] = false;
		
		$swiper_data_init['navigation']['nextEl'] = "#swiper-button-next-".$random_number;
		$swiper_data_init['navigation']['prevEl'] = "#swiper-button-prev-".$random_number;
		$swiper_data_init['breakpoints']['0']['slidesPerView'] = 2;
		$swiper_data_init['breakpoints']['0']['spaceBetween'] = 20;
		$swiper_data_init['breakpoints']['480']['slidesPerView'] = 2;
		$swiper_data_init['breakpoints']['480']['spaceBetween'] = 30;
		$swiper_data_init['breakpoints']['639']['slidesPerView'] = 3;
		$swiper_data_init['breakpoints']['639']['spaceBetween'] = 30;
		$swiper_data_init['breakpoints']['768']['slidesPerView'] = 4;
		$swiper_data_init['breakpoints']['768']['spaceBetween'] = 30;
		$swiper_data_init['breakpoints']['1200']['slidesPerView'] = $items_per_slider;
		$swiper_data_init['breakpoints']['1200']['spaceBetween'] = 30;
?>
<div id="<?php echo $slider_id;?>"  data-swiper='<?php echo json_encode($swiper_data_init);?>'class="subcategory-grid <?php echo $sliderClass; ?>">
<div class="<?php echo $sliderWarperClass; ?>">
	<?php
	foreach ($category_all_childs as $key => $catId) {
           //$_category = $block->_categoryModel->create()->load($catId);
		   $_category = $_objectManager->create('Magento\Catalog\Model\CategoryFactory')->create()->load($catId);
          if(($_category->getId())&&($_category->getIsActive())):
			$_outputhelper = $this->helper('Magebees\CategoryImage\Helper\Category');
            $subcaturl = $_category->getUrl();
			$_imgHtml = '';
			if($_category->getThumbnail()):
			$_imgUrl = $_helper->getThumbnailImageUrl($_category);
			$_imgPath = $pubPath.$_helper->getThumbnailImagePath($_category);
			list($width, $height) = @getimagesize($_imgPath);
			$_imgHtml = '<img loading="lazy" src="' . $_imgUrl . '" alt="' . $_category->getName() . '" title="' . $_category->getName() . '" width="' . $width . '" height="' . $height . '"/><div class="swiper-lazy-preloader-white"></div>';
			else:
			$_imgUrl= $mediaURL.'poco/catthumbnail/dummy-image.jpg';	
			$_imgPath= $pubPath.'media/poco/catthumbnail/dummy-image.jpg';
			list($width, $height) = @getimagesize($_imgPath);
			$_imgHtml = '<img loading="lazy" src="' . $_imgUrl . '" alt="' . $_category->getName() . '" title="' . $_category->getName() . '" width="' . $width . '" height="' . $height . '"/><div class="swiper-lazy-preloader-white"></div>';
			 endif;
			
            /* @escapeNotVerified */
            echo '<div class='.$sliderItemClass.'>
					<a href="' . $subcaturl . '" class="block-promo product photo product-item-photo" title="' . $_category->getName() . '">' . $_imgHtml . '</a>
					<div class="product name product-item-name"><a href="' . $subcaturl . '" title="' . $_category->getName() . '">' . $_category->getName() . '</a></div>
				  </div>';
           endif;
    } 
	?>
</div>
<div id="<?php echo "swiper-button-next-".$random_number;?>" class="swiper-button-next"></div>
<div id="<?php echo "swiper-button-prev-".$random_number;?>" class="swiper-button-prev"></div>
</div>
<?php endif; ?>