<script>
require(['Magento_Ui/js/modal/confirm','prototype'], function(confirmation){

//<![CDATA[
    function import<?php echo $block->getImportType(); ?>() {
		confirmation({
			title: 'Import CMS <?php echo $block->getImportType(); ?>',
			content: 'Do you really want to import CMS <?php echo $block->getImportType(); ?>?',
			actions: {
				confirm: function(){
					var resultMessage = $('import_result<?php echo $block->getImportType(); ?>');
					params = {
						import_type: '<?php echo $block->getImportType(); ?>',
						//demo_version: document.getElementById('pocoinstall_install_demo_version').value,
						overwrite: document.getElementById('<?php echo $block->getThemeName(); ?>_install_overwrite_<?php echo $block->getImportType(); ?>').value
					};

					new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
						parameters: params,
						onSuccess: function(response) {
							var validationMessage = document.getElementById("import_result<?php echo $block->getImportType(); ?>");
							var result = '<?php echo __('Error during Import CMS Datas.') ?>';
							try {
								if (response.responseText.isJSON()) {
									response = response.responseText.evalJSON();
									result = response.message;
								}
								if (response.valid == 1) {
									validationMessage.removeClassName('hidden').addClassName('success').addClassName('message-success')
								} else {
									validationMessage.removeClassName('hidden').addClassName('error').addClassName('message-error')
								}
							} catch (e) {
								validationMessage.removeClassName('hidden').addClassName('error').addClassName('message-error')
							}
							validationMessage.update(result);
							/*setTimeout(function(){
								location.reload();
							},3000);*/
						}
					});
				},
				cancel: function(){},
				always: function(){}
			}
		});
	
        
    }

    window.import<?php echo $block->getImportType(); ?> = import<?php echo $block->getImportType(); ?>;
//]]>

});
</script>
<style type="text/css">
#import_result<?php echo $block->getImportType(); ?>:before{
    top: 20px;
    margin: 0;
}
</style>
<div class="actions actions-import-data">
    <button onclick="javascript:import<?php echo $block->getImportType(); ?>(); return false;" class="action-import-data" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="import_result<?php echo $block->getImportType(); ?>" class="message-validation hidden message"></div>
</div>
