<?php
namespace Magebees\PocoThemes\Console\Command;

class AdvertisementData
{
    /**
     * Get advertisement information
     * @return array
     */
    public static function getAdvertisementInformation()
    {
        $magebees_advertisement_information = [
		  ['advertisement_id' => '1','block_name' => 'Poco Theme Furniture ','pattern' => '29','status' => '1','unique_code' => 
		NULL],
		  ['advertisement_id' => '2','block_name' => 'Electronic Theme Home Pattern 30','pattern' => '30','status' => '1',
		'unique_code' => NULL],
		  ['advertisement_id' => '3','block_name' => 'Electronic Theme Home Pattern 31','pattern' => '31','status' => '1',
		'unique_code' => NULL],
		  ['advertisement_id' => '4','block_name' => 'Poco Theme Decor','pattern' => '32','status' => '1','unique_code' => NULL],
		  ['advertisement_id' => '5','block_name' => 'Footwear Layout','pattern' => '33','status' => '1','unique_code' => NULL],
		  ['advertisement_id' => '6','block_name' => 'Poco Theme Jewellery','pattern' => '34','status' => '1','unique_code' => NULL],
		  ['advertisement_id' => '7','block_name' => 'Vitamin Pattern Banners','pattern' => '34','status' => '1','unique_code' => NULL],
		   ['advertisement_id' => '8','block_name' => 'Guns Advertisement Banners','pattern' => '2','status' => '1','unique_code' => NULL],
			['advertisement_id' => '9','block_name' => 'Guns Advertisement Banners','pattern' => '35','status' => '1','unique_code' => NULL],
			['advertisement_id' => '10','block_name' => 'Bakery Advertisement','pattern' => '36','status' => '1','unique_code' => NULL],
			['advertisement_id' => '11','block_name' => 'Mega Store - Pattern 6','pattern' => '6','status' => '1','unique_code' => NULL],
			['advertisement_id' => '12','block_name' => 'Mage Store - Pattern 7','pattern' => '7','status' => '1','unique_code' => NULL],
			['advertisement_id' => '13','block_name' => 'Pet - Pattern 37','pattern' => '37','status' => '1','unique_code' => NULL]
		];
		return  $magebees_advertisement_information;
		
    }
	
	public static function getAdvertisementImages(){
		$magebees_advertisement_images = [
		  ['image_id' => '4','advertisement_id' => '1','filename' => '/s/m/small-banner1.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#252524','heading_text_size' => '38px','hover_heading_text' => '<b>Stool</b>','show_hover_heading_text' => '1','short_text_color' => '#6c6c6c','short_text_size' => '16px','hover_short_text' => '83 Items','show_hover_short_text' => '1','button_text' => 'Shop Now','button_text_size' => '15px','button_bg_color' => '#ffffff','button_text_color' => '#252524','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'table.html','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '441','image_width' => '660'],
		  ['image_id' => '5','advertisement_id' => '1','filename' => '/s/m/small-banner2.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#252524','heading_text_size' => '38px','hover_heading_text' => '<b>Chair</b>','show_hover_heading_text' => '1','short_text_color' => '#6c6c6c','short_text_size' => '16px','hover_short_text' => '65 Items','show_hover_short_text' => '1','button_text' => 'Shop Now','button_text_size' => '15px','button_bg_color' => '#ffffff','button_text_color' => '#252524','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'chair.html','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '441','image_width' => '660'],
		  ['image_id' => '6','advertisement_id' => '1','filename' => '/s/m/small-banner3.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#252524','heading_text_size' => '38px','hover_heading_text' => '<b>Light</b>','show_hover_heading_text' => '1','short_text_color' => '#6c6c6c','short_text_size' => '16px','hover_short_text' => '40 Items','show_hover_short_text' => '1','button_text' => ' Shop Now','button_text_size' => '20px','button_bg_color' => '#ffffff','button_text_color' => '#6c6c6c','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'office-chairs.html','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '450','image_width' => '430'],
		  ['image_id' => '7','advertisement_id' => '1','filename' => '/s/m/small-banner4.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '38px','hover_heading_text' => '<b>WOODEN <br>MAGIC</b>','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => '','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '0','image_effect' => 'zoomin','advertise_url' => 'study-tables.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '450','image_width' => '430'],
		  ['image_id' => '8','advertisement_id' => '1','filename' => '/s/m/small-banner5.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#252524','heading_text_size' => '38px','hover_heading_text' => '<b>Tea Stool</b>','show_hover_heading_text' => '1','short_text_color' => '#6c6c6c','short_text_size' => '16px','hover_short_text' => '35 Items','show_hover_short_text' => '1','button_text' => ' Shop Now','button_text_size' => '20px','button_bg_color' => '#ffffff','button_text_color' => '#6c6c6c','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'chair.html','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '450','image_width' => '430'],
		  ['image_id' => '14','advertisement_id' => '2','filename' => '/b/l/bluethooth.png','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '28px','hover_heading_text' => 'Bluetooth <br>speaker','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'BUY NOW','button_text_size' => '14px','button_bg_color' => '#282c3d','button_text_color' => '#ffffff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => '','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '290','image_width' => '463'],
		  ['image_id' => '15','advertisement_id' => '2','filename' => '/l/a/laptop.png','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '28px','hover_heading_text' => 'Modern and <br>style laptop','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'BUY NOW','button_text_size' => '14px','button_bg_color' => '#e7fd40','button_text_color' => '#282c3d','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => '','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '290','image_width' => '463'],
		  ['image_id' => '16','advertisement_id' => '2','filename' => '/e/a/earbuds.png','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '28px','hover_heading_text' => 'Wireless <br>earbuds','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'BUY NOW','button_text_size' => '14px','button_bg_color' => '#282c3d','button_text_color' => '#ffffff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => '','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '290','image_width' => '463'],
		  ['image_id' => '17','advertisement_id' => '3','filename' => '/h/e/headphone.png','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '28px','hover_heading_text' => 'New Collection <br><b>headphone</b>','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'View More','button_text_size' => '14px','button_bg_color' => '#282c3d','button_text_color' => '#ffffff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => '','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '218','image_width' => '710'],
		  ['image_id' => '18','advertisement_id' => '3','filename' => '/w/i/wireless.png','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '28px','hover_heading_text' => 'Wireless <br><b>Speaker</b>','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '1','button_text' => 'View More','button_text_size' => '14px','button_bg_color' => '#282c3d','button_text_color' => '#ffffff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => '','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '218','image_width' => '710'],
		  ['image_id' => '19','advertisement_id' => '4','filename' => '/w/o/wooden-pot.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '','heading_text_size' => '14','hover_heading_text' => 'Wooden pot','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'Shop Now','button_text_size' => '14','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'wooden-pot.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '337','image_width' => '387'],
		  ['image_id' => '20','advertisement_id' => '4','filename' => '/s/h/show-piece.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '','heading_text_size' => '14','hover_heading_text' => 'Show piece','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'Shop Now','button_text_size' => '12','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'show-piece.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '337','image_width' => '387'],
		  ['image_id' => '21','advertisement_id' => '4','filename' => '/h/o/home-decor.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '','heading_text_size' => '14','hover_heading_text' => 'Home decor','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'Shop Now','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'home-decor.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '337','image_width' => '387'],
		  ['image_id' => '22','advertisement_id' => '4','filename' => '/l/i/light-lamp.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '','heading_text_size' => '14','hover_heading_text' => 'Light Lamp','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'Shop Now','button_text_size' => '12','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'light-lamp.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '337','image_width' => '387'],
		  ['image_id' => '23','advertisement_id' => '4','filename' => '/w/a/wall-clock.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '','heading_text_size' => '14','hover_heading_text' => 'Wall Clock','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'Shop Now','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'wall-clock.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '704','image_width' => '805'],
		  ['image_id' => '24','advertisement_id' => '5','filename' => '/n/e/newst-deal.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '50px','hover_heading_text' => 'NEWEST<br/>DEALS','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => 'Big Sale 15% Off','show_hover_short_text' => '1','button_text' => 'Buy Now','button_text_size' => '','button_bg_color' => '','button_text_color' => '#ffffff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'running-shoes.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '415','image_width' => '530'],
		  ['image_id' => '25','advertisement_id' => '5','filename' => '/s/n/sneckers.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '24px','hover_heading_text' => 'WITH AN INCREDIBLY <b>SOFT FEEL</b>','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => 'Sports Shoes','show_hover_short_text' => '0','button_text' => '','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '0','image_effect' => 'zoomin','advertise_url' => 'men-collection/sneakers.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '415','image_width' => '530'],
		  ['image_id' => '26','advertisement_id' => '5','filename' => '/s/p/sports_shoes.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '50px','hover_heading_text' => 'SPORTS<br/>SHOES','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => 'Upto 20% Off','show_hover_short_text' => '1','button_text' => 'Buy Now','button_text_size' => '','button_bg_color' => '','button_text_color' => '#ffffff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'running-shoes.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '415','image_width' => '530'],
		  ['image_id' => '27','advertisement_id' => '6','filename' => '/j/e/jewellery-ad1.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#b69664','heading_text_size' => '32px','hover_heading_text' => 'Earrings','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '20px','hover_short_text' => '39% off','show_hover_short_text' => '1','button_text' => 'SHOP NOW','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'gold-nose-pins.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '262','image_width' => '450'],
		  ['image_id' => '28','advertisement_id' => '6','filename' => '/j/e/jewellery-ad2.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '30px','hover_heading_text' => 'Super discount for <br/> your first purchase','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '14px','hover_short_text' => 'DISCOVER SALE','show_hover_short_text' => '1','button_text' => 'FREE20FIRST','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'gold-ring.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '262','image_width' => '450'],
		  ['image_id' => '29','advertisement_id' => '6','filename' => '/j/e/jewellery-ad3.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#b69664','heading_text_size' => '32px','hover_heading_text' => 'Necklaces','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '20px','hover_short_text' => '24% off','show_hover_short_text' => '1','button_text' => 'SHOP NOW','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'gold-bangles.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '262','image_width' => '450'],
		  ['image_id' => '30','advertisement_id' => '7','filename' => '/p/t/ptn-bnr1.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '30px','hover_heading_text' => 'Protein<br> powder','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '16px','hover_short_text' => 'Muscleblaze','show_hover_short_text' => '1','button_text' => 'SHOP NOW','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#1b1b1b','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'protein-powder.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '262','image_width' => '450'],
		  ['image_id' => '31','advertisement_id' => '7','filename' => '/p/t/ptn-bnr2.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#1b1b1b','heading_text_size' => '22px','hover_heading_text' => 'Superior results<br/> Awards 2023','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => '','button_text_size' => '','button_bg_color' => '','button_text_color' => '','show_button_text' => '0','image_effect' => 'zoomin','advertise_url' => '','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '262','image_width' => '450'],
		  ['image_id' => '32','advertisement_id' => '7','filename' => '/p/t/ptn-bnr3.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '30px','hover_heading_text' => 'Increase<br> energy','show_hover_heading_text' => '1','short_text_color' => '#fff','short_text_size' => '16px','hover_short_text' => 'Kids increase','show_hover_short_text' => '1','button_text' => 'SHOP NOW','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#1b1b1b','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'daily-vitamins.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '262','image_width' => '450'],
		  ['image_id' => '33','advertisement_id' => '8','filename' => '/s/m/small-banner6.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#1e1e1e','heading_text_size' => '45px','hover_heading_text' => 'Certified <br/>used guns','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => 'Confidence','show_hover_short_text' => '1','button_text' => 'YOUR GUN','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#1e1e1e','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'vintage-gun.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '300','image_width' => '590'],
		 ['image_id' => '34','advertisement_id' => '8','filename' => '/s/m/small-banner7.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#1e1e1e','heading_text_size' => '45px','hover_heading_text' => 'Shotguns <br/>equipment','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => 'Got upgrading','show_hover_short_text' => '1','button_text' => 'SHOP NOW','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#1e1e1e','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'shotguns.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '300','image_width' => '590'],
		 ['image_id' => '35','advertisement_id' => '9','filename' => '/s/m/small-banner8.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#1e1e1e','heading_text_size' => '45px','hover_heading_text' => 'Certified <br/>used guns','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => 'Confidence','show_hover_short_text' => '1','button_text' => 'YOUR GUN','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#1e1e1e','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'vintage-gun.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '338','image_width' => '710'],
		 ['image_id' => '36','advertisement_id' => '9','filename' => '/s/m/small-banner9.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#1e1e1e','heading_text_size' => '45px','hover_heading_text' => 'Shotguns <br/>equipment','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => 'Got upgrading','show_hover_short_text' => '1','button_text' => 'SHOP NOW','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#1e1e1e','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'shotguns.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '338','image_width' => '710'],
		 ['image_id' => '37','advertisement_id' => '10','filename' => '/c/o/cookie.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#fff','heading_text_size' => '45px','hover_heading_text' => 'Coconut<br/>cookies','show_hover_heading_text' => '1','short_text_color' => '#e5b830','short_text_size' => '20px','hover_short_text' => 'Special kids','show_hover_short_text' => '1','button_text' => 'Order now','button_text_size' => '18px','button_bg_color' => '#e4b730','button_text_color' => '#fff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'cookie.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '294','image_width' => '708'],
		  ['image_id' => '38','advertisement_id' => '10','filename' => '/d/o/donut.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#fff','heading_text_size' => '45px','hover_heading_text' => 'Delicious<br/>donuts','show_hover_heading_text' => '1','short_text_color' => '#fff','short_text_size' => '20px','hover_short_text' => 'kids favourite','show_hover_short_text' => '1','button_text' => 'Order now','button_text_size' => '18px','button_bg_color' => '#303030','button_text_color' => '#fff','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'donut.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '294','image_width' => '708'],
		  ['image_id' => '39','advertisement_id' => '11','filename' => '/p/t/pt6-1.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#2e2e2e','heading_text_size' => '24px','hover_heading_text' => 'HEADPHONE <br/><b>COLLECTION</b>','show_hover_heading_text' => '1','short_text_color' => '#282828','short_text_size' => '18px','hover_short_text' => 'Free shipping over order $120','show_hover_short_text' => '0','button_text' => 'SHOP NOW','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#282828','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'prime-videos.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '421','image_width' => '390'],
		['image_id' => '40','advertisement_id' => '11','filename' => '/p/t/pt6-2.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#282828','heading_text_size' => '47px','hover_heading_text' => 'LETS <br/><b>HAVE FUN<br/> BE FIT!</b>','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'SPORTS EQUIPMENT','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#282828','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'health-beauty.html','text_position' => '1','unique_code' => NULL,'external_url' => '0','image_height' => '421','image_width' => '810'],
		['image_id' => '41','advertisement_id' => '11','filename' => '/p/t/pt6-3.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#282828','heading_text_size' => '24px','hover_heading_text' => 'KITCHEN <br /><b>ESSENTIALS</b>','show_hover_heading_text' => '1','short_text_color' => '','short_text_size' => '','hover_short_text' => '','show_hover_short_text' => '0','button_text' => 'SHOP NOW','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#282828','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'home-kitchen.html','text_position' => '3','unique_code' => NULL,'external_url' => '0','image_height' => '421','image_width' => '390'],
		['image_id' => '42', 'advertisement_id' => '12', 'filename' => '/p/t/pt7-1.jpg', 'display_text_mode' => '1', 'show_image' => '1', 'bg_color' => '', 'heading_text_color' => '#282828', 'heading_text_size' => '32px', 'hover_heading_text' => 'Ultralight <br />comfort', 'show_hover_heading_text' => '1', 'short_text_color' => '#282828', 'short_text_size' => '18px', 'hover_short_text' => '20% DISCOUNT', 'show_hover_short_text' => '1', 'button_text' => 'SEE MORE', 'button_text_size' => '14px', 'button_bg_color' => '#ffffff', 'button_text_color' => '#282828', 'show_button_text' => '1', 'image_effect' => 'zoomin', 'advertise_url' => 'shooes.html', 'text_position' => '1', 'unique_code' => '', 'external_url' => '0', 'image_height' => '283', 'image_width' => '530'],
		['image_id' => '43', 'advertisement_id' => '12', 'filename' => '/p/t/pt7-2.jpg', 'display_text_mode' => '1', 'show_image' => '1', 'bg_color' => '', 'heading_text_color' => '#ffffff', 'heading_text_size' => '38px', 'hover_heading_text' => 'Don’t miss this! use code', 'show_hover_heading_text' => '1', 'short_text_color' => '#ffffff', 'short_text_size' => '22px', 'hover_short_text' => 'EXTRA 30% OFF ALL ELEMENTS', 'show_hover_short_text' => '1', 'button_text' => 'USE CODE: UBONE30', 'button_text_size' => '14px', 'button_bg_color' => '#e0e54e', 'button_text_color' => '#282828', 'show_button_text' => '1', 'image_effect' => 'zoomin', 'advertise_url' => 'tv-audios.html', 'text_position' => '1', 'unique_code' => '', 'external_url' => '0', 'image_height' => '283', 'image_width' => '530'],
		['image_id' => '44', 'advertisement_id' => '12', 'filename' => '/p/t/pt7-3.jpg', 'display_text_mode' => '1', 'show_image' => '1', 'bg_color' => '', 'heading_text_color' => '#282828', 'heading_text_size' => '32px', 'hover_heading_text' => 'Headphone <br/>on word off', 'show_hover_heading_text' => '1', 'short_text_color' => '#282828', 'short_text_size' => '18px', 'hover_short_text' => 'MIN. 40% OFF', 'show_hover_short_text' => '1', 'button_text' => 'SEE MORE', 'button_text_size' => '14px', 'button_bg_color' => '#ffffff', 'button_text_color' => '#282828', 'show_button_text' => '1', 'image_effect' => 'zoomin', 'advertise_url' => 'headphones.html', 'text_position' => '1', 'unique_code' => '', 'external_url' => '0', 'image_height' => '283', 'image_width' => '530'],
		
		
		['image_id' => '48','advertisement_id' => '13','filename' => '/p/a/patern-37-1_1.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '38px','hover_heading_text' => 'Best product <br/>Pets food','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => '<span>*50% off </span> all products','show_hover_short_text' => '1','button_text' => 'Shop Now','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#000000','show_button_text' => '0','image_effect' => 'zoomin','advertise_url' => 'pets-toys.html','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '433','image_width' => '463'],
    ['image_id' => '49','advertisement_id' => '13','filename' => '/p/a/patern-37-2.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#373530','heading_text_size' => '26px','hover_heading_text' => '<b>Improve</b> the <br/>pets products','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '14px','hover_short_text' => 'SALE UP TO 30%','show_hover_short_text' => '0','button_text' => 'Shop Now','button_text_size' => '16px','button_bg_color' => '#ffffff','button_text_color' => '#373530','show_button_text' => '1','image_effect' => 'zoomin','advertise_url' => 'pets-food.html','text_position' => '2','unique_code' => NULL,'external_url' => '0','image_height' => '433','image_width' => '463'],
    ['image_id' => '50','advertisement_id' => '13','filename' => '/p/a/patern-37-3.jpg','display_text_mode' => '1','show_image' => '1','bg_color' => '','heading_text_color' => '#ffffff','heading_text_size' => '38px','hover_heading_text' => 'Natural healthy<br/> cat food','show_hover_heading_text' => '1','short_text_color' => '#ffffff','short_text_size' => '18px','hover_short_text' => 'Get up to <span>20% off</span>','show_hover_short_text' => '1','button_text' => 'Shop Now','button_text_size' => '14px','button_bg_color' => '#ffffff','button_text_color' => '#000000','show_button_text' => '0','image_effect' => 'zoomin','advertise_url' => 'walk-essentials.html','text_position' => '0','unique_code' => NULL,'external_url' => '0','image_height' => '433','image_width' => '463']


		];
		return $magebees_advertisement_images;
		
	}
}
