<?php
namespace Magebees\PocoThemes\Console\Command;

class PagebannerData {
	public static function getPagebanner($page_baanner_store_id){
		$magebees_pagebanner = [
			['banner_id' => '10','title' => 'Customer Login','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_account_login','banner_image' => '/p/a/page-banner-10.jpg'],
			['banner_id' => '11','title' => 'FAQ\'s','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'faqs','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-11.jpg'],
			['banner_id' => '12','title' => 'About Us','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'about-us','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-12.jpg'],
			['banner_id' => '13','title' => 'About Us Modern','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'about-modern','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-13.jpg'],
			['banner_id' => '14','title' => 'Contact Us','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'contact_index_index','banner_image' => '/p/a/page-banner-14.jpg'],
			['banner_id' => '15','title' => 'Privacy policy','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'privacy-policy','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-15.jpg'],
			['banner_id' => '16','title' => 'Payment policy','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'payment-policy','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-16.jpg'],
			['banner_id' => '17','title' => 'Return policy','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'return-policy','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-17.jpg'],
			['banner_id' => '18','title' => 'Terms & condition','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'terms-condition','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-18.jpg'],
			['banner_id' => '19','title' => 'Page 404 Found','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => 'no-route','catalog_category' => '','blog_category' => '','layout_handle' => 'cms_index_defaultnoroute','banner_image' => '/p/a/page-banner-19.jpg'],
			['banner_id' => '20','title' => 'Catalog Category','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'catalog_category_view','banner_image' => '/p/a/page-banner-20.jpg'],
			['banner_id' => '34','title' => 'CMS Page Banner','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'cms_page_view','banner_image' => '/p/a/page-banner-34.jpg'],
			['banner_id' => '43','title' => 'Blog Category Banner','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'blog_category_view','banner_image' => '/p/a/page-banner-43.jpg'],
			['banner_id' => '45','title' => 'Forgot Your Password?','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_account_forgotpassword','banner_image' => '/p/a/page-banner-45.jpg'],
			['banner_id' => '46','title' => 'Create New Customer Account','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_account_create','banner_image' => '/p/a/page-banner-46.jpg'],
			['banner_id' => '47','title' => 'Catalog Product Compare','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'catalog_product_compare_index','banner_image' => '/p/a/page-banner-47.jpg'],
			['banner_id' => '48','title' => 'Catalog Product View','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'catalog_product_view','banner_image' => '/p/a/page-banner-48.jpg'],
			['banner_id' => '50','title' => 'CMS No Route Page','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'cms_noroute_index','banner_image' => '/p/a/page-banner-50.jpg'],
			['banner_id' => '51','title' => 'Shopping Cart','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_cart_index','banner_image' => '/p/a/page-banner-51.jpg'],
			['banner_id' => '52','title' => 'Page 404','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'cmspage','cms_page' => 'no-route','catalog_category' => '','blog_category' => '','layout_handle' => '','banner_image' => '/p/a/page-banner-52.jpg'],
			['banner_id' => '53','title' => 'One Page Checkout','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_index_index','banner_image' => '/p/a/page-banner-53.jpg'],
			['banner_id' => '54','title' => 'One Page Checkout Payment Method','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_onepage_paymentmethod','banner_image' => '/p/a/page-banner-54.jpg'],
			['banner_id' => '55','title' => 'One Page Checkout Shipping Mehtod','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_onepage_shippingmethod','banner_image' => '/p/a/page-banner-55.jpg'],
			['banner_id' => '56','title' => 'One Page Checkout  Failure','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_onepage_failure','banner_image' => '/p/a/page-banner-56.jpg'],
			['banner_id' => '57','title' => 'One Page Checkout Overview','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_onepage_review','banner_image' => '/p/a/page-banner-57.jpg'],
			['banner_id' => '60','title' => 'Blog Page','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'blog_index_index','banner_image' => '/p/a/page-banner-60.jpg'],
			['banner_id' => '250','title' => 'Blog With Tags','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'blog_tag_view','banner_image' => '/p/a/page-banner-250.jpg'],
			['banner_id' => '251','title' => 'Blog Archive','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'blog_archive_index','banner_image' => '/p/a/page-banner-251.jpg'],
			['banner_id' => '252','title' => 'Blog Search','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'blog_search_index','banner_image' => '/p/a/page-banner-252.jpg'],
			['banner_id' => '253','title' => 'Blog Detail Page','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'blog_post_view','banner_image' => '/p/a/page-banner-253.jpg'],
			['banner_id' => '256','title' => 'One Page Checkout','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_index_index','banner_image' => '/p/a/page-banner-256.jpg'],
			['banner_id' => '257','title' => 'One page checkout success','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'checkout_onepage_success','banner_image' => '/p/a/page-banner-257.jpg'],
			['banner_id' => '260','title' => 'My Account','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_account_index','banner_image' => '/p/a/page-banner-260.jpg'],
			['banner_id' => '261','title' => 'Edit Account','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_address_form','banner_image' => '/p/a/page-banner-261.jpg'],
			['banner_id' => '262','title' => 'Customer Account Edit','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_account_edit','banner_image' => '/p/a/page-banner-262.jpg'],
			['banner_id' => '264','title' => 'My Wishlist','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'wishlist_index_share','banner_image' => '/p/a/page-banner-264.jpg'],
			['banner_id' => '265','title' => ' Stored Payment Methods','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'vault_cards_listaction','banner_image' => '/p/a/page-banner-265.jpg'],
			['banner_id' => '266','title' => 'Customer My Account Product Reviews','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'review_customer_index','banner_image' => '/p/a/page-banner-266.jpg'],
			['banner_id' => '267','title' => 'Customer My Account My Wish List','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'wishlist_index_index','banner_image' => '/p/a/page-banner-267.jpg'],
			['banner_id' => '268','title' => 'Newsletter Subscription','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'newsletter_manage_index','banner_image' => '/p/a/page-banner-268.jpg'],
			['banner_id' => '269','title' => 'My Downloadable Products','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'downloadable_customer_products','banner_image' => '/p/a/page-banner-269.jpg'],
			['banner_id' => '270','title' => 'Order','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'sales_order_view','banner_image' => '/p/a/page-banner-270.jpg'],
			['banner_id' => '271','title' => 'Review Details','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'review_customer_view','banner_image' => '/p/a/page-banner-271.jpg'],
			['banner_id' => '272','title' => ' Address Book','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_address_index','banner_image' => '/p/a/page-banner-272.jpg'],
			['banner_id' => '273','title' => 'Logout Success','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'customer_account_logoutsuccess','banner_image' => '/p/a/page-banner-273.jpg'],
			['banner_id' => '276','title' => 'Search results','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'catalogsearch_result_index','banner_image' => '/p/a/page-banner-276.jpg'],
			['banner_id' => '278','title' => 'My Orders','stores' => $page_baanner_store_id,'status' => '1','page_type_options' => 'specifiedpage','cms_page' => '','catalog_category' => '','blog_category' => '','layout_handle' => 'sales_order_history','banner_image' => '/p/a/page-banner-278.jpg']
		];
		return $magebees_pagebanner;
	}
}