<?php
namespace Magebees\PocoThemes\Console\Command;

class ResponsivebannersliderData {
	public static function getResponsivebannersliderGroup(){
		$responsivebannerslider_group = [
			['slidergroup_id' => '1','title' => 'Poco Themes Home Page Furniture Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '1','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '0','smooth_height' => '1','max_width' => '','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '777777','pagination_active' => '000000','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-furniture-slider','scrollbar' => '0','keyboard' => '1','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '2','title' => 'Poco Themes Home Page Fashion Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '0','smooth_height' => '0','max_width' => '1920','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom_left','pagination_color' => '','pagination_active' => 'rgba(0,0,0,0.2)','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-fashion-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '3','title' => 'Poco Themes Home Page Cosmetic Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'fade','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '0','smooth_height' => '0','max_width' => '1920','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'always','pagination_style' => 'fraction_bar','pagination_position' => 'inside_bottom_right','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-cosmetic-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '4','title' => 'Poco Themes Home Page Electronic Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '0','smooth_height' => '0','max_width' => '1920','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => 'FFFFFF','show_pagination' => 'always','pagination_style' => 'circular','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#FFFFFF','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-electronic-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '#FFFFFF','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '5','title' => 'Poco Themes Home Page Autoparts Slider','position' => 'content_bottom','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '7000','random_order' => '0','smooth_height' => '0','max_width' => '1920','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'always','pagination_style' => 'fraction_bar','pagination_position' => 'inside_bottom','pagination_color' => '#ffffff','pagination_active' => '#ece908','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-autoparts-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '6','title' => 'Poco Themes Home Page Medical Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '0','smooth_height' => '0','max_width' => '','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-medical-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '7','title' => 'Poco Themes Home Page Kids Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '7000','random_order' => '0','smooth_height' => '0','max_width' => '','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'never','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '223A57','pagination_active' => 'FFFA6C','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-kids-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '','pagination_bocolor' => '','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '8','title' => 'Poco Themes Home Page Fashion 2 Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '0','smooth_height' => '0','max_width' => '1920','slider_theme' => 'default','slider_type' => 'basic','content_background' => '','content_opacity' => '','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => 'inside','navigation_acolor' => '333333','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom_left','pagination_color' => '','pagination_active' => '#FFFFFF','pagination_bar' => 'E5E5E5','unique_code' => 'poco-themes-home-page-fashion-2-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '','pagination_bocolor' => '#FFFFFF','space_between' => '0','slides_per_view' => NULL,'grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '9','title' => 'Poco Themes Home Page Decor Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '9000','random_order' => '','smooth_height' => '1','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-themes-home-page-decor-slider','scrollbar' => '0','keyboard' => '1','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '#000000','pagination_bocolor' => '','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '10','title' => 'Poco Theme Home Page Footwear Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '10000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'never','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-theme-home-page-footwear-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '1','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '3','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '12','title' => 'Poco Theme Home Page Jewellery Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '10000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-theme-home-page-jewellery-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '13','title' => 'Poco Theme Home Page Vitamin Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '10000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'always','pagination_style' => 'fraction_bar','pagination_position' => 'inside_bottom_right','pagination_color' => '#ffffff','pagination_active' => '#ffffff','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-theme-home-page-vitamin-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '14','title' => 'Poco Theme Home Page Guns Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '8000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'always','navigation_style' => 'style4','navigation_aposition' => '','navigation_acolor' => '#ffffff','show_pagination' => 'never','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => '','unique_code' => 'poco-theme-home-page-guns-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '15','title' => 'Poco Theme Home Page Gaming Accessories Slider','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '10000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'never','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-theme-home-page-gaming-accessories-slider','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '16','title' => 'Poco Theme Home Page Gaming Accessories Slider RTL','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '0','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '10000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'always','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'never','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-theme-home-page-gaming-accessories-slider-rtl','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			['slidergroup_id' => '17','title' => 'Poco Theme Home Page Bakery','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '0','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'slide','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '10000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'always','navigation_style' => 'style4','navigation_aposition' => '','navigation_acolor' => '#ffffff','show_pagination' => 'never','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'rgba(0, 0, 0, 0.5)','unique_code' => 'poco-theme-home-page-bakery','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#000000','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1'],
			 ['slidergroup_id' => '18','title' => 'Poco Theme Home Page - Pets','position' => 'content_top','sort_order' => '0','status' => '1','start_animation' => '1','loop_slider' => '1','pause_snavigation' => '0','pause_shover' => '0','animation_type' => 'fade','animation_duration' => '600','animation_direction' => 'horizontal','slide_duration' => '7000','random_order' => '','smooth_height' => '0','max_width' => '','slider_theme' => '','slider_type' => 'basic','content_background' => '','content_opacity' => '9','thumbnail_size' => '200','navigation_arrow' => 'never','navigation_style' => 'style1','navigation_aposition' => '','navigation_acolor' => '#0f0f0f','show_pagination' => 'always','pagination_style' => 'numbers','pagination_position' => 'inside_bottom','pagination_color' => '','pagination_active' => '#ffffff','pagination_bar' => 'rgba(255, 255, 255, 0.5)','unique_code' => 'poco-theme-home-page---pets','scrollbar' => '0','keyboard' => '0','mousewheel' => '1','grab' => '0','banner_content_tcolor' => '#373530','pagination_bocolor' => '#ffffff','space_between' => '0','slides_per_view' => '1','grid_view' => NULL,'grid_per_view' => NULL,'lazy_load' => '1']
		];
		return $responsivebannerslider_group;
	}
	
	public static function getResponsivebannersliderSlide(){
		$responsivebannerslider_slide = [
			['slide_id' => '1','group_names' => '1','titles' => 'Poco Themes Furniture - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/u/furniture-slide-1.jpg','alt_text' => 'Poco Themes Furniture Demo 1 - Slide 1','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<div class="offers-text">GET 25% OFF USE CODE: <strong>STELLA25</strong></div>
			<h2 class="mega-title"><strong>arm chair</strong></h2>
			<p class="small-text">Furniture that is too obviously<br>designed is very interesting.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '991','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '3','group_names' => '2','titles' => 'Poco Themes Fashion - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/a/fashion-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h4 class="small-title">The new collection</h4>
			<div class="mega-title"><b>QUILTED<br>COMFORT</b></div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Collections','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '935','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '4','group_names' => '2','titles' => 'Poco Themes Fashion - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/a/fashion-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h4 class="small-title">The new collection 2023</h4>
			<div class="mega-title"><b>COMFORT<br/> FASHION</b></div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '935','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '5','group_names' => '1','titles' => 'Poco Themes Furniture - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/u/furniture-slide-2.jpg','alt_text' => 'Poco Themes Furniture Demo 1 - Slide 2','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<div class="offers-text">GET 25% OFF USE CODE: <strong>STELLA30</strong></div>
			<h2 class="mega-title"><strong>tea table</strong></h2>
			<p class="small-text">Furniture that is too obviously<br>designed is very interesting.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '991','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '6','group_names' => '1','titles' => 'Poco Themes Furniture - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/u/furniture-slide-3.jpg','alt_text' => 'Poco Themes Furniture Demo 1 - Slide 3','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<div class="offers-text">GET 70% OFF USE CODE: <strong>STELLA70</strong></div>
			<h2 class="mega-title"><strong>office chair</strong></h2>
			<p class="small-text">Furniture that is too obviously<br>designed is very interesting.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '991','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '7','group_names' => '3','titles' => 'Poco Themes Cosmetic - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/c/o/cosmetic-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Makeup fun<br>and <em>helps</em> us<br>feel better</h2>
			<p class="small-text">Natural ingredients.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1020','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '11','group_names' => '3','titles' => 'Poco Themes Cosmetic - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/c/o/cosmetic-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Everyone is<br><em>beautiful,</em> we just<br>ake it clear!</h2>
			<p class="small-text">One of everything really good</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1020','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '12','group_names' => '3','titles' => 'Poco Themes Cosmetic - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/c/o/cosmetic-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Say help to<br>the <em>best</em> skin<br>of your life</h2>
			<p class="small-text">The best makeup brands</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1020','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '13','group_names' => '4','titles' => 'Poco Themes Electronic - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/e/l/electronic-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title fw-300">Bluetooth<br><strong>speaker</strong></h2>
			<div class="slr_cnt">
			<div class="text">Speaker model<br><span class="text-upprcase">Stella speaker - DG650</span></div>
			<div class="text">Connector<br><span class="text-upprcase">Audio input, USB Type-c</span></div>
			</div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Buy Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '903','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '14','group_names' => '4','titles' => 'Poco Themes Electronic - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/e/l/electronic-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title fw-300">smart<br><strong>watches</strong></h2>
			<div class="slr_cnt">
			<div class="text">Mouse model<br><span class="text-upprcase">LOGITECH PC MOUSE</span></div>
			<div class="text">Connector<br><span class="text-upprcase">BLUETOOTH, WIRELESS</span></div>
			</div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Buy Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '903','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '15','group_names' => '4','titles' => 'Poco Themes Electronic - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/e/l/electronic-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title fw-300">Beard<br><strong>Trimmer</strong></h2>
			<div class="slr_cnt">
			<div class="text">Operation Type<br><span class="text-upprcase">Standard Battery Life: 120 Min</span></div>
			<div class="text">Trimming Range<br><span class="text-upprcase">0.5mm to 16mm</span></div>
			</div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Buy Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '903','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '16','group_names' => '5','titles' => 'Poco Themes Autoparts - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/a/u/autoparts-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'leftBottom','description' => '<h2 class="mega-title fw-800 w_text">AUTO<br>PARTS</h2>
			<p class="small-text w_text">100 trusted car auto parts</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Auto parts','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1020','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '17','group_names' => '5','titles' => 'Poco Themes Autoparts - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/a/u/autoparts-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'leftBottom','description' => '<h2 class="mega-title fw-800 w_text">QUALITY<br>USED</h2>
			<p class="small-text w_text">Free nationwide shipping</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '3','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1020','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '18','group_names' => '5','titles' => 'Poco Themes Autoparts - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/a/u/autoparts-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'leftBottom','description' => '<h2 class="mega-title fw-800 w_text">ONE STOP <br>SOLUTION</h2>
			<p class="small-text w_text">100 trusted car auto parts</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '2','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1020','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '19','group_names' => '6','titles' => 'Poco Themes Medical - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/m/e/medical-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title">The right choice<br>for your health<br>care needs</h2>
			<p class="small-text">Helpline number: <a href="tel:0123-456-789">0123-456-789</a></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Free consultation','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1080','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '20','group_names' => '6','titles' => 'Poco Themes Medical - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/m/e/medical-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title">Perfect choice<br>for your medical<br>equipment</h2>
			<p class="small-text">Helpline number: <a href="tel:0123-456-789">0123-456-789</a></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Free Inquiry','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1080','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '21','group_names' => '6','titles' => 'Poco Themes Medical - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/m/e/medical-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title">Choosing the<br>right medical<br>uniform</h2>
			<p class="small-text">Helpline number: <a href="tel:0123-456-789">0123-456-789</a></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Free Inquiry','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '1080','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '22','group_names' => '7','titles' => 'Poco Themes Kids - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/k/i/kids_banner.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Simplicity<br>and comfort</h2>
			<p class="small-text">Children are not things to be molded,<br>but are people to be unfolded.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Explore Now','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '940','image_width' => '1820','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '23','group_names' => '8','titles' => 'Poco Themes Fashion 2 - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/a/fashion-2-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h4 class="small-title">Hipster fashion store</h4>
			<div class="mega-title"><strong>QUILTED<br>COMFORT</strong></div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Collections','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '937','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '24','group_names' => '8','titles' => 'Poco Themes Fashion 2 - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/a/fashion-2-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h4 class="small-title">Hipster fashion store</h4>
			<div class="mega-title"><strong>APPAREL<br>COMFORT</strong></div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '1','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Collections','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '937','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '25','group_names' => '8','titles' => 'Poco Themes Fashion 2 - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/a/fashion-2-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h4 class="small-title">Best seller items</h4>
			<div class="mega-title"><strong>FASHION<br>SPIRIT</strong></div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '2','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop Collections','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '937','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '26','group_names' => '2','titles' => 'Poco Themes Fashion - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/a/fashion-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h4 class="small-title">The new collection</h4>
			<div class="mega-title"><strong>SUMMER<br>DRESS</strong></div>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Collection','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '935','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '27','group_names' => '9','titles' => 'Poco Themes Decor - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/d/e/decor-slide-1.jpg','alt_text' => 'Poco Themes Decor - Slide 1','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">Decoration collection</p>
			<h2 class="mega-title">Wooden<br>crafting</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop collection <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '733','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '28','group_names' => '9','titles' => 'Poco Themes Decor - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/d/e/decor-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">Decoration collection</p>
			<h2 class="mega-title">Wooden<br>lamp</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop collection <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '733','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '29','group_names' => '9','titles' => 'Poco Themes Decor - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/d/e/decor-slide-3.jpg','alt_text' => '','url' => '#','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">Essentials collection</p>
			<h2 class="mega-title">Wooden<br>chair</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Shop collection <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '733','image_width' => '1920','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '30','group_names' => '10','titles' => 'Poco Themes Footwear - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/o/footwear-slide-1.jpg','alt_text' => 'Poco Themes Footwear - Slide 1','url' => '#','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title"><strong>MEN</strong> COLLECTION</h2>
			<p class="small-text">End of season sale! 30% off! USE CODE <u>STLL30</u></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '1','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Explore now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '640','image_width' => '640','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '31','group_names' => '10','titles' => 'Poco Themes Footwear - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/o/footwear-slide-2.jpg','alt_text' => 'Poco Themes Footwear - Slide 2','url' => '#','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title"><strong>WOMEN</strong> COLLECTION</h2>
			<p class="small-text">20% off for all products! USE CODE <u>STLL20</u></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '2','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Explore now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '640','image_width' => '640','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '32','group_names' => '10','titles' => 'Poco Themes Footwear - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/o/footwear-slide-3.jpg','alt_text' => 'Poco Themes Footwear - Slide 3','url' => '','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title"><strong>KIDS</strong> COLLECTION</h2>
			<p class="small-text">Amazing price reduction! <u>NEW ARRIVALS<u></u></u></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '3','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Explore now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '640','image_width' => '640','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '33','group_names' => '10','titles' => 'Poco Themes Footwear - Slide 4','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/o/footwear-slide-4.jpg','alt_text' => 'Poco Themes Footwear - Slide 4','url' => '','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title"><strong>UNISEX</strong> COLLECTION</h2>
			<p class="small-text">40% off for all products! USE CODE <u>STLL40</u></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '5','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Explore now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '640','image_width' => '640','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '34','group_names' => '10','titles' => 'Poco Themes Footwear - Slide 5','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/f/o/footwear-slide-5.jpg','alt_text' => 'Poco Themes Footwear - Slide 5','url' => '','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title"><strong>SNKRS</strong> COLLECTION</h2>
			<p class="small-text">Season sale! 10% OFF! USE CODE <u>STLL10</u></p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '4','statuss' => '1','filename_mobile' => NULL,'btnone_text' => 'Explore now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '640','image_width' => '640','mobile_image_height' => '','mobile_image_width' => '','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '36','group_names' => '12','titles' => 'Poco Themes Jewellery - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/j/e/jewellery-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Sparkle<br>and shine</h2>
			<p class="small-text">A unique design, Intangible quality.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg> <span>Shop collection</span>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '787','image_width' => '1920','mobile_image_height' => '328','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '37','group_names' => '12','titles' => 'Poco Themes Jewellery - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/j/e/jewellery-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Solitaire <br />Eternally</h2>
			<p class="small-text">Timeless. Tested. Loved.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg> <span>Shop collection</span>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '787','image_width' => '1920','mobile_image_height' => '328','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '38','group_names' => '12','titles' => 'Poco Themes Jewellery - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/j/e/jewellery-slide-3.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<h2 class="mega-title">Necklace <br/>rated love</h2>
			<p class="small-text">Let your style shine.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg> <span>Shop collection</span>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '787','image_width' => '1920','mobile_image_height' => '328','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '39','group_names' => '13','titles' => 'Poco Themes Vitamin - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/v/i/vitamin-slide-1.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">100% pure organic tablets</p>
			<h2 class="mega-title">Life is a tragedy <br>of nutrition</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> <span>Shop Product</span>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '804','image_width' => '1920','mobile_image_height' => '350','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '40','group_names' => '13','titles' => 'Poco Themes Vitamin - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/v/i/vitamin-slide-2.jpg','alt_text' => '','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">It\'s all about nutrition.</p>
			<h2 class="mega-title">Perfect body<br>with nutrition</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> <span>Shop Product</span>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '804','image_width' => '1920','mobile_image_height' => '350','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '41','group_names' => '13','titles' => 'Poco Themes Vitamin - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/v/i/vitamin-slide-3.jpg','alt_text' => 'Poco Themes Vitamin - Slide 3','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">Nutrition is so important.</p>
			<h2 class="mega-title">The excitement <br>of vitamins</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => NULL,'btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> <span>Shop Product</span>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '804','image_width' => '1920','mobile_image_height' => '350','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '42','group_names' => '14','titles' => 'Poco Themes Guns - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/g/u/gun-slide-1.jpg','alt_text' => 'Poco Themes Guns - Slide 1','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<p class="small-text">Action double 12 rounds handguns</p>
			<h2 class="mega-title">9MM LUGER<br>AUTOMATIC</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '','btnone_text' => 'Purchase now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => 'handguns.html','btntwo_text' => '','btntwo_url' => '','image_height' => '803','image_width' => '1920','mobile_image_height' => '395','mobile_image_width' => '900','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '43','group_names' => '14','titles' => 'Poco Themes Guns - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/g/u/gun-slide-2.jpg','alt_text' => 'Poco Themes Guns - Slide 2','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<p class="small-text">Preserving a legacy for generations to come</p>
			<h2 class="mega-title">HERITAGE<br>MFG.</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '','btnone_text' => 'Purchase now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => 'vintage-gun.html','btntwo_text' => '','btntwo_url' => '','image_height' => '803','image_width' => '1920','mobile_image_height' => '395','mobile_image_width' => '900','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '44','group_names' => '14','titles' => 'Poco Themes Guns - Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/g/u/gun-slide-3.jpg','alt_text' => 'Poco Themes Guns - Slide 3','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<p class="small-text">Ready, Aim save! Shop the best deal on guns</p>
			<h2 class="mega-title">DEAL OF <br/>THE WEEK</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '','btnone_text' => 'Purchase now <svg xmlns="https://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>','btnone_url' => 'ammunition.html','btntwo_text' => '','btntwo_url' => '','image_height' => '803','image_width' => '1920','mobile_image_height' => '395','mobile_image_width' => '900','show_offer_text' => '0','offer_text' => ''],
			['slide_id' => '45','group_names' => '15','titles' => 'Poco Themes Gaming Accessories - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/g/a/gaming-slide-1.jpg','alt_text' => 'Poco Themes Gaming Accessories - Slide 1','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">Next-generation gaming sensor</p>
			<h2 class="mega-title">Best gaming<br>perspective</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '','btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg> <span>Shop Collection</span>','btnone_url' => 'game-monitor.html','btntwo_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg> <span>How to use</span>','btntwo_url' => '#','image_height' => '1070','image_width' => '1920','mobile_image_height' => '612','mobile_image_width' => '1073','show_offer_text' => '1','offer_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="19" y1="5" x2="5" y2="19"></line><circle cx="6.5" cy="6.5" r="2.5"></circle><circle cx="17.5" cy="17.5" r="2.5"></circle></svg> <span>Member discount<br/>On every order over $99.00</span>'],
			['slide_id' => '46','group_names' => '15','titles' => 'Poco Themes Gaming Accessories - Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/g/a/gaming-slide-2.jpg','alt_text' => 'Poco Themes Gaming Accessories - Slide 2','url' => '','url_target' => 'same_window','content_position' => 'left','description' => '<p class="small-text">Next-generation gaming sensor</p>
			<h2 class="mega-title">Best gaming<br>perspective</h2>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '','btnone_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg> <span>Shop Collection</span>','btnone_url' => 'game-monitor.html','btntwo_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg> <span>How to use</span>','btntwo_url' => '#','image_height' => '1070','image_width' => '1920','mobile_image_height' => '612','mobile_image_width' => '1073','show_offer_text' => '1','offer_text' => '<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="19" y1="5" x2="5" y2="19"></line><circle cx="6.5" cy="6.5" r="2.5"></circle><circle cx="17.5" cy="17.5" r="2.5"></circle></svg> <span>Member discount<br/>On every order over $99.00</span>'],
			['slide_id' => '47','group_names' => '17','titles' => 'Poco Themes Bakery- Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/b/a/bakery-slide-1.jpg','alt_text' => 'Poco Themes Bakery- Slide 1','url' => '','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title">DELICIOUS<br>FRESHLY</h2>
			<p class="small-text">life. love. eat.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '/b/a/bakery-slide-m-1.jpg','btnone_text' => '','btnone_url' => '','btntwo_text' => '','btntwo_url' => '','image_height' => '1001','image_width' => '1920','mobile_image_height' => '890','mobile_image_width' => '1333','show_offer_text' => '0','offer_text' => NULL],
			['slide_id' => '48','group_names' => '17','titles' => 'Poco Themes Bakery- Slide 2','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/b/a/bakery-slide-2.jpg','alt_text' => 'Poco Themes Bakery- Slide 2','url' => '','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title">DAILY FRESH<br>BAKED GOODS</h2>
			<p class="small-text">life. love. eat.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '/b/a/bakery-slide-m-2.jpg','btnone_text' => '','btnone_url' => '','btntwo_text' => '','btntwo_url' => '','image_height' => '1001','image_width' => '1920','mobile_image_height' => '890','mobile_image_width' => '1333','show_offer_text' => '0','offer_text' => NULL],
			['slide_id' => '49','group_names' => '17','titles' => 'Poco Themes Bakery- Slide 3','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/b/a/bakery-slide-3.jpg','alt_text' => 'Poco Themes Bakery- Slide 3','url' => '','url_target' => 'same_window','content_position' => 'centerBottom','description' => '<h2 class="mega-title">QUALITY BREAD<br>AND PASTRY</h2>
			<p class="small-text">life. love. eat.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '/b/a/bakery-slide-m-3.jpg','btnone_text' => '','btnone_url' => '','btntwo_text' => '','btntwo_url' => '','image_height' => '1001','image_width' => '1920','mobile_image_height' => '890','mobile_image_width' => '1333','show_offer_text' => '0','offer_text' => NULL],
			['slide_id' => '50','group_names' => '18','titles' => 'Poco Themes Pets - Slide 1','img_video' => 'image','img_hosting' => '0','video_id' => '','hosted_url' => '','hosted_thumb' => '','filename' => '/s/l/slide-1-pets.jpg','alt_text' => 'Poco Themes Pets - Slide 1','url' => '','url_target' => 'same_window','content_position' => 'right','description' => '<h2 class="mega-title">All natural<br>dog treats!</h2>
<p class="small-text">Animals are such agreeable friends. They<br>ask no questions they pass no criticisms.</p>','date_enabled' => '0','from_date' => NULL,'to_date' => NULL,'sort_order' => '0','statuss' => '1','filename_mobile' => '/s/l/slide-mbl-1_1.webp','btnone_text' => '<span class="text">Shop collection</span> <svg xmlns="https://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg>','btnone_url' => '#','btntwo_text' => '','btntwo_url' => '','image_height' => '955','image_width' => '1920','mobile_image_height' => '455','mobile_image_width' => '800','show_offer_text' => '0','offer_text' => NULL]
		];
		return $responsivebannerslider_slide;
	}

}