<?php
/**
 * Template for displaying today deal products
 *
 * @var $block \Magebees\PocoThemes\Block\DealProducts
 */
 
	$block->getDealProductsCollection();
	$product = $this->getProduct();
	$deal_pro_ids = $this->_dealProductIds;
	
	if(in_array($product->getId(),$deal_pro_ids)){
		$timer = $block->getCountTimer();
		echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
			->setData('count_time', $timer)
			->setisCategoryPage(true)
			->setTemplate("Magebees_TodayDealProducts::timer.phtml")->toHtml();
	}
?>

    
            
  
