<?php
/**
 * Template for displaying today deal products
 *
 * @var $block \Magebees\TodayDealProducts\Block\DealProducts
 */
use Magento\Framework\App\Action\Action;
 
$exist = ($block->getProductCollection() && $block->getProductCollection()->getSize() && (bool)$block->getConfigValues('enabled'));

if ((bool)$block->getConfigValues('enabled')) {
    $type = 'widget-new-grid';
    $mode = 'grid';
    $imageDisplayArea = 'new_products_content_widget_grid';
    $title = __($block->getDealData('title'));
    $deal_description = __($block->getDealData('description'));
    $items = $block->getProductCollection()->getItems();

    $showWishlist = (bool)$block->getWishlist();
    $showCompare = (bool)$block->getCompare();
    $showCart = (bool)$block->getCart();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    //$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = (bool)$block->getProductDescription();
    $showPrice = (bool)$block->getPrice();
    $timer = $block->getCountTimer();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
	$productsCount = count($block->getProductCollection()->getData());
	
	$viewMode = 'grid';
	$showDescription = false;

	/* POCO THEME CUSTOMIZATION ADD CODE Start */ 
	include ($block->getTemplateFile('Magento_Catalog::product/product-list-theme-options.phtml'));
	/* POCO THEME CUSTOMIZATION ADD CODE End */ 
	$bg_color = $this->getWdBgcolor();
	if($this->getWdBgimage()){
		$bg_image_url = $poco_helper->getMediaUrl().$this->getWdBgimage();
		$bg_image = 'background-image: url('.$bg_image_url.'); background-repeat: no-repeat; background-size: cover;';
	}else{
		$bg_image = '';
	}
	$spacing_class = '';
	$spacing_class .= $this->getWdSpacing()?'sections-spacing ':'';
	$spacing_class .= $this->getWdBottomSpacing() ? 'section-bottom-spacing' : '';
	$show_view_all = $this->getWdShowViewall();
	$view_all_txt = $this->getWdViewallTxt();
	$view_all_url = $this->getWdViewallUrl();
?>

<?php if(($bg_image)||($bg_color)): ?>
<style type="text/css">
	<?php echo '#mage-deal-products-'.$randon_number. " { ".$bg_image."; background-color: ".$bg_color."; } " ?>
</style>
 <?php endif;?>
     <div id="<?php echo "mage-deal-products-".$randon_number; ?>" class="mage-products mage-deal-products mage-deal-products-style2 <?php /* @escapeNotVerified */ echo $mode; ?> <?php echo $spacing_class ?>">
        <div class="block-title d_fl alc jcb">
			<?php if(($title)&&($show_deal_title)):?>
            	<div class="flex-1"><h2 class="title" role="heading" aria-level="2"><?php echo __(html_entity_decode($title)); ?></h2></div>
           	<?php endif; ?>
            <div class="flex-1">
				<?php if($show_deal_timer): ?>
					<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setData('count_time', $timer)->setTemplate("Magebees_TodayDealProducts::timer.phtml")->toHtml();?>
				<?php endif; ?>
			</div>
        <div class="block-content">
		<?php if($block->getDealData('description')): ?>
            <p class="deal-description"><?php echo $block->escapeHtml($deal_description); ?></p>
			<?php endif; ?>
            <?php /* @escapeNotVerified */ echo '<!-- ' . $imageDisplayArea . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="product-items <?php /* @escapeNotVerified */ echo $type; ?> <?php echo $btn_hover_effects_class; ?>">
                    <?php 
						/* Set Condition for Sample Data Start */
						if(!$productsCount): $slider = false; echo $this->getLayout() ->createBlock('Magento\Framework\View\Element\Template') ->setProductCount($productsCount) ->setSlider($slider) ->setImageWidth($image_width) ->setImageHeight($image_height) ->setTemplate('Magebees_Productlisting::dummy-products-grid.phtml') ->toHtml();
						 endif; /* Set Condition for Sample Data End */
						?>
					<?php foreach ($items as $_item) : ?>
                      <div class="item product product-item">  
                       <div class="product-item-info" data-container="product-grid">
							<div class="pro-hover">
								<div class="product-item-photo">
									<a href="<?php echo $_item->getProductUrl() ?>" tabindex="-1">
										<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template") ->setProduct($_item) ->setAspectRatio($aspect_ratio) ->setImageWidth($image_width) ->setImageHeight($image_height) ->setDisplayArea($imageDisplayArea) ->setTemplate("Magento_Catalog::product/image.phtml") ->toHtml();?>
									</a>
									<?php if(($show_deal_timer)&&(($hover_effects == 'button-hover-style7')||($hover_effects == 'button-hover-style11'))): ?>
											<!--Deal Timer On Hover Style7 Or 11 -->
											<?php echo $this->getLayout()->createBlock('Magebees\TodayDealProducts\Block\DealTimerListingProducts')->setProduct($_item) ->setTemplate('Magebees_TodayDealProducts::category_page_timer.phtml')->toHtml(); ?>
											<!--End Deal Timer On Hover Style7 Or 11 -->
									<?php endif; ?>
								</div>
								
								<?php if(($hover_effects != 'button-hover-style7')&&($hover_effects != 'button-hover-style11')): ?>
									<!--Buttons Hover Styles-->
									<?php echo $this->getLayout()->createBlock('Magebees\PocoThemes\Block\AddToButtons') ->setProduct($_item) ->setDisplayTimer(false) ->setShowCart($show_cart) ->setShowWishlist($show_wishlist) ->setShowCompare($show_compare) ->setShowAjaxQuickView($ajaxquickview_enable) ->setCurrentAction($currentAction) ->
							setAddCartIcon($add_cart_icon)->setWishlistIcon($whishlist_icon)->setCompareIcon($compare_icon)->setQuickviewIcon($quick_view_icon)->toHtml(); ?>
									
									<!--End Buttons Hover Styles-->
								<?php endif; ?>
							</div>

							<div class="product-item-details">
                                <div class="detail-left">
									<?php if($show_product_category): echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template") ->setProduct($_item) ->setStoreId($storeId) ->setTemplate ("Magento_Catalog::product/category-link.phtml") ->toHtml(); endif; ?>

                                    <?php if($show_product_brand_name): ?>
										<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template") ->setProduct($_item) ->setStoreId($storeId) ->setBrandCode($brand_attribute_code) ->setBrandUrlKey($brand_url_key) ->setBaseUrl($webUrl) ->setTemplate ("Magento_Catalog::product/brand-link.phtml") ->toHtml(); ?>
									<?php endif; ?>
								
									<strong class="product name product-item-name">
                                        <a class="product-item-link" href="<?php echo $_item->getProductUrl() ?>"> <?php echo $_helper->productAttribute($_item, $_item->getName(), 'name'); ?> </a>
                                    </strong>

                                    <?php if($show_product_rating): ?>
                                		<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true); ?>
                            		<?php endif; ?>

									<?php if($show_product_sku): ?>
										<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template") ->setProduct($_item) ->setProductSkuLabel($product_sku_label) ->setProductSkuSeparator($product_sku_separator) ->setTemplate("Magento_Catalog::product/product-sku.phtml") ->toHtml();?>
									<?php endif; ?>
							
									<?php if(($hover_effects != 'button-hover-style10')&&($show_product_price)): ?>                        
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
									<?php endif; ?>

							 		<?php if($buyNowEnabled): echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template") ->setProduct($_item) ->setButtonTitle($buyNowbuttonTitle) ->setBuyNowListProduct($buyNowListProduct) ->setTemplate("Magento_Catalog::product/buy-now.phtml") ->toHtml(); endif; ?>

                                    <?php echo $block->getProductDetailsHtml($_item); ?>

                                    <?php $_productNameStripped = $block->stripTags($_item->getName(), null, true); ?>
                                    
									<?php if(!$this->getShowSlider()):?>
										<?php if ($this->getDescription()):?>
											<div class="product description product-item-description">
												<?php echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
												<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="action secondary more"><?php echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									<?php endif; ?>

									<!--Show Configurable Product Swatches -->
									<?php if($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magebees_Swatches::product/listing/renderer.phtml");	echo $swatchBlock->setProduct($_item)->toHtml(); } ?>
									<!--End Configurable Product Swatches -->
								</div>

								<?php if((($hover_effects == 'button-hover-style10')||($hover_effects == 'button-hover-style12'))&&($allow_add_to_cart)): ?>
												<!-- Button Hover Style 10 Or 12 Start -->
												<div class="d-flex alc  <?php echo $bottom_btn_hover_effects_class; ?> hvr_dtl">
												<?php if(($hover_effects == 'button-hover-style10')&&($show_product_price)): ?>
											<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
										<?php endif; ?>
										<div class="actions-primary" >
											<?php if ($_item->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_item); ?>
												<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey') ?>
													<?php $isHasOptions = $_item->getTypeInstance()->hasOptions($_item);?>
													<?php if($isHasOptions): $add_to_cart_btn_title = 'Select Option'; endif; ?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__($add_to_cart_btn_title)); ?>"
															class="action tocart primary">
															<?php echo $add_cart_icon; ?>
														<span><?php echo __($add_to_cart_btn_title) ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php echo __('Sold Out') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>	
									<!--End Buttons Hover Styles 10 Or 12 -->
		                    	<?php endif; ?>

								<?php if(($hover_effects == 'button-hover-style7')||($hover_effects == 'button-hover-style11')): ?>
                            		<!--Buttons Hover Styles 7 OR 11 -->
									<?php echo $this->getLayout()->createBlock('Magebees\PocoThemes\Block\AddToButtons') ->setProduct($_item) ->setDisplayTimer(false) ->setShowCart($show_cart) ->setShowWishlist($show_wishlist) ->setShowCompare($show_compare) ->setShowAjaxQuickView($ajaxquickview_enable) ->setCurrentAction($currentAction) ->
							setAddCartIcon($add_cart_icon)->setWishlistIcon($whishlist_icon)->setCompareIcon($compare_icon)->setQuickviewIcon($quick_view_icon)->toHtml(); ?>
									<!--End Buttons Hover Styles  7 OR 11 -->
								<?php endif; ?>
							</div>
						</div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
		
		<?php if($block->getWdShowViewall()): $view_all_text = $block->getWdViewallTxt()?$block->getWdViewallTxt():'View All Collection'; ?>
			<div class="view-more <?php echo $animation_class ?>" <?php if($animation): ?>data-wow-delay="0.7s" <?php endif;?>><a href="<?php echo $block->getViewAllUrl($block->getWdViewallUrl());?>" title="<?php echo __(html_entity_decode($block->escapeHtml($view_all_text))); ?> " class="readMore action primary"><?php echo __(html_entity_decode($block->escapeHtml($view_all_text))); ?> </a></div>
		<?php endif; ?>
		
    </div>
<?php } ?>
