<?php 
$helper = $this->helper('Magebees\Responsivebannerslider\Helper\Data');
$slide_groups = $helper->getAllGroup();
$dynamic_static_file_dir = $this->getDynamicStaticTemplateDirectoryPath();
$dir = $helper->getStaticTemplateDirectoryPath($dynamic_static_file_dir);
$developer_mode = $helper->enabledDevmode();
if($developer_mode){
	$developer_mode = 0;
}else{
	$developer_mode = 1;
}
?>
<script type="text/javascript">
    //<![CDATA[
	 function publishMenu() {
		// getStaticfilesList();
		
		 var developermodeStatus = <?php echo $developer_mode; ?>;
		 if(!developermodeStatus){
			var slide_groups = <?php echo json_encode($slide_groups); ?>;
			var dir = '<?php echo $dir;?>';
			var file_list = new Array() ; 
			jQuery.each(slide_groups, function(idx, slidegroup) {
			
				var slideGroupId = slidegroup.value;



				if(slideGroupId){
					var myFile = dir+"banner-"+slideGroupId+".html";
					var temp = new Array() ;
					temp[0] = slideGroupId;
					temp[1] = myFile;
					file_list.push(temp);						
				}
			});	 
		 }
		
		new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
	            if (transport.responseText){
						if(!developermodeStatus){
						generateStaticMenuHtml(file_list);
						}else{
						alert(transport.responseText);
					}
				}
            }
        });
    }
	function generateStaticMenuHtml(file_list)
	{ 
		jQuery.ajax({
			url : '<?php echo $this->getGenerateStaticMenuUrl() ?>',
			data: { 
			'file_list' :JSON.stringify(file_list),
				form_key: FORM_KEY
			} ,
			dataType: 'json',
			type: 'post',
			showLoader:true,
			success: function(response){
				try {
					file_list.shift();
					if(response.next==true){ 
						generateStaticMenuHtml(file_list);
					}else{
						location.reload();
					}
					if(response.error_message){
						alert(response.error_message);
					}
					}catch(e){
						if(response.error_message){
							alert(response.error_message);
						}
					}
		}
		});
	}
    //]]>
</script>
<?php echo $this->getButtonHtml() ?>