<?php 
$randon_number = rand();	
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$galleryThumbanailWidgetData = $this->getData(); 

if(count($galleryThumbanailWidgetData)>0): 
$galleryWidgetEmptyOptions = array('template'=>null,'wd_spacing'=>null,'wd_bottom_spacing'=>null,'wd_show_heading'=>null,'wd_heading'=>null,'wd_show_description'=>null,'wd_description_position'=>null,'wd_description'=>null,'no_of_image'=>null,'wd_slider'=>null,'wd_items_per_slide'=>null,'wd_items_per_row'=>null,'wd_autoscroll'=>null,'wd_auto_play_dealytime'=>null,'wd_autoplayoff'=>null,'wd_slide_auto_height'=>null,'wd_navarrow'=>null,'wd_pagination'=>null,'wd_auto_play_delaytime'=>null,'wd_infinite_loop'=>null,'wd_scrollbar'=>null,'wd_grap_cursor'=>null,'store_id'=>null,'wd_bgcolor'=>null,'wd_bgimage'=>null);
$galleryWidget = array();
$ajaxLoadingData = array();
$ajaxLoadingData['randon_number'] = $randon_number;
$ajaxLoadingData['url'] = $block->getUrl('imagegallery/index/ajaxload');
$ajaxLoadingData['res_div'] = '#galleryThumbanail'.$randon_number;
$ajaxLoadingData['loading_div'] = '#loadingImage'.$randon_number;
$ajaxLoadingData['loaderUrl'] = $poco_helper->getLoadingIcon(); 
$galleryWidget['ajaxloading'] = (array_merge($galleryWidgetEmptyOptions,$galleryThumbanailWidgetData,$ajaxLoadingData));
?>
<div id="galleryThumbanail<?php echo $randon_number; ?>" class="ajx_loader" data-mage-init='<?php echo $poco_helper->getJsonEncode($galleryWidget);?>'>
<div id="loadingImage<?php echo $randon_number; ?>" style="display:none;"></div>
</div>
<?php endif; ?>