<?php 
$_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$image_path = 'Magebees_Productlisting::images/dummy-product-image.jpg';
$_imgUrl=$this->getViewFileUrl("Magebees_Productlisting::images/dummy-product-image.jpg");
$image_width = $block->getImageWidth();
$image_height = $block->getImageHeight();
if ($image_width && $image_height) {
		$ratio = $image_height / $image_width;
	}else{
	$ratio = 1;
}

$productsCount = $block->getProductCount();
$slider = $block->getSlider();
$animation = $block->getAnimation();
$animation_class = $animation?"wow animate__fadeIn":" ";
$slider_class = $slider?" swiper":" ";
$item_class =   $slider?"item product product-item swiper-slide":"item product product-item";
$products = array(
array('productId'=>1,'name'=>'Example Product Title','url'=>"#",'price'=>50,'specialprice'=>null),
array('productId'=>2,'name'=>'Example Product Title','url'=>"#",'price'=>68,'specialprice'=>null),
array('productId'=>3,'name'=>'Example Product Title','url'=>"#",'price'=>75,'specialprice'=>39),
array('productId'=>4,'name'=>'Example Product Title','url'=>"#",'price'=>99,'specialprice'=>null),
array('productId'=>5,'name'=>'Example Product Title','url'=>"#",'price'=>129,'specialprice'=>99),
array('productId'=>6,'name'=>'Example Product Title','url'=>"#",'price'=>149,'specialprice'=>119),
array('productId'=>7,'name'=>'Example Product Title','url'=>"#",'price'=>37,'specialprice'=>null),
array('productId'=>8,'name'=>'Example Product Title','url'=>"#",'price'=>225,'specialprice'=>199),
array('productId'=>9,'name'=>'Example Product Title','url'=>"#",'price'=>250,'specialprice'=>null),
array('productId'=>10,'name'=>'Example Product Title','url'=>"#",'price'=>349,'specialprice'=>null),
array('productId'=>11,'name'=>'Example Product Title','url'=>"#",'price'=>280,'specialprice'=>249),
array('productId'=>12,'name'=>'Example Product Title','url'=>"#",'price'=>300,'specialprice'=>259));

?> 
<?php 
$count=0;
if(!$productsCount){
	$productsCount = count($products);
}
foreach ($products as $product): 
if($count < $productsCount):
$count++;
?>
<?php $productPrice =  $_helper->getFormattedPrice($product['price']);?>
<div class="<?php echo $item_class;?>">			
<div class="product-item-info" data-container="product-grid">
	<div class="pro-hover">
		<a href="<?php echo $product['url'];?>" class="product photo product-item-photo" tabindex="-1">
		<span class="product-image-container" style="width:<?=$image_width ?>px;">
		<span class="product-image-wrapper" style="padding-bottom: <?= /* @escapeNotVerified */ ($ratio * 100) ?>%;">
			<img class="product-image-photo" loading="lazy" src="<?php echo $_imgUrl;?>" alt="<?php echo $product['name'];?>" width="<? echo $image_width; ?>" height="<? echo $image_height; ?>">
		</span>
		</span>
		</a>
	</div>
	<div class="product details product-item-details">	
		<div class="detail-left">
			<strong class="product-item-name">
							<a title="<?php echo $product['name'];?>" href="<?php echo $product['url'];?>" class="product-item-link">
							<?php echo $product['name'];?>
							</a>
			 </strong>
			 <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $product['productId'];?>" data-price-box="product-id-<?php echo $product['productId'];?>">
			 <?php if((isset($product['specialprice']))&&($product['specialprice'])>0): ?>
			 <?php $productSpecialPrice =  $_helper->getFormattedPrice($product['specialprice']);?>
			 <span class="special-price">
				<span class="price-container price-final_price tax weee">
				<span class="price-label"><?php echo 'Special Price';?></span>
				<span id="product-price-<?php echo $product['productId'];?>" data-price-amount="<?php echo $product['specialprice'];?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo $productSpecialPrice;?></span></span>
				</span>
			</span>
			
			<span class="old-price">
				<span class="price-container price-final_price tax weee">
					<span class="price-label"><?php echo 'Regular Price';?></span>
					<span id="product-price-<?php echo $product['productId'];?>" data-price-amount="<?php echo $product['price'];?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo $productPrice;?></span>
					</span>
				</span>
			</span>
			
			 <?php else:?>
			 <span class="normal-price">
				<span class="price-container price-final_price tax weee">
					<span class="price-label"><?php echo 'As low as';?></span>
					<span id="product-price-<?php echo $product['productId'];?>" data-price-amount="<?php echo $product['price'];?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo $productPrice;?></span>
					</span>
				</span>
			</span>
			 <?php endif;?>
			 
			</div>	
		</div>
	</div>
</div>
</div>
<?php endif;?>
<?php endforeach;?>
