<?php
/**
 * Copyright © 2018 Magebees, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* $block Magebees\CustomCartStyle\Block\MiniCart */
?>

<div class="minicart-popup" id="poco-minicart-popup" data-block='minicartpro' style="display:none;">
    <div id="minicartpro-content-wrapper" class="minicartpro-content-wrapper" data-bind="scope: 'minicartpro_content'">
        <!-- ko template: 'Magebees_CustomCartStyle/minicart/content-popup.html' --><!-- /ko -->
    </div>
    <div class="ajaxcart-loader double-bounce-spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>

<script type="text/x-magento-init">
{
	"[data-block='minicartpro']": {
		"Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
	}
}
</script>