<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
 $_helper = $this->helper('Magebees\Pagebanner\Helper\Data');
/*if($_helper->isEnablePageBanner()){
$pageBanner = $_helper->getPageBanner();
$pageBannerHtml = '';
if($pageBanner->getBannerId()){
$image = $pageBanner->getBannerImage();
$bannerImage = $_helper->getBannerImagePath($image);
$pageBannerHtml = '<img src="'.$bannerImage.'" alt="'.$pageBanner->getTitle().'" title="'.$pageBanner->getTitle().'" class="image">';
}

$banner_image_class = 'noimage';
if($pageBannerHtml):
	$banner_image_class = '';
endif;	
}else{
	$banner_image_class = 'noimage';
}*/

if(($_helper->isEnablePageBanner())&&($_helper->isPageBannerExist())){
$banner_image_class = '';
}else{
	$banner_image_class = 'noimage';
}

if($_helper->isProductPage()):
	$banner_image_class = '';
endif;
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';

if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?> <?= $block->escapeHtmlAttr($banner_image_class) ?>">
    <h1 class="page-title"
        <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()) : ?>
            aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
        <?php endif; ?>>
        <?= /* @noEscape */ $titleHtml ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>