<div class="entry-edit">
	<div class="entry-edit-head">
		<h3 class="icon-head head-edit-form fieldset-legend"><?php echo 'Template Tag'; ?></h3>
    </div>
        
            
        
<textarea id="flexslider-template-tag" rows="3" cols="80" onclick="this.focus();this.select()" readonly="readonly">{{block class="Magebees\Productlisting\Block\Productlisting" listing_id="<?php echo $block->getProductlistingData(); ?>"}}</textarea>

</div>
<br><br>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h3 class="icon-head head-edit-form fieldset-legend"><?php echo 'XML Code'; ?></h3>
    </div>
        
        
        
<textarea id="flexslider-code" rows="7" cols="80" onclick="this.focus();this.select()" readonly="readonly"><referenceContainer name="content">
    <block class="Magebees\Productlisting\Block\Productlisting" name="listing<?php echo $block->getProductlistingData(); ?>">
        <arguments>
        	<argument name="listing_id" xsi:type="string"><?php echo $block->getProductlistingData(); ?></argument>
    	</arguments>
    </block>
</referenceContainer></textarea>
</div>

<br><br>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h3 class="icon-head head-edit-form fieldset-legend"><?php echo 'Call Via Frontend Template File'; ?></h3>
    </div>
    
        
        
<textarea id="flexslider-template-tag" rows="3" cols="80" onclick="this.focus();this.select()" readonly="readonly"><?php echo '<?php echo  $this->getLayout()->createBlock("Magebees\Productlisting\Block\Productlisting")->setListingId('. $block->getProductlistingData().')->toHtml() ?>'; ?></textarea>
</div>

