<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magebees\PocoThemes\Block\Html\Header $block
 */
?>
<?php $poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data'); 
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$storeId = $poco_helper->getStoreId();
$headerConfig =$poco_helper->getConfigGroup('header',$storeId);
$font_icons = $poco_helper->getConfigGroup('font_icons',$storeId);
$_cacheHelper = $this->helper('Magebees\PocoThemes\Helper\Cache');
$top_header = array_key_exists('top_header', $headerConfig) ? $headerConfig['top_header'] : false;
$social_media_enable = array_key_exists('social_media_enable', $headerConfig) ? $headerConfig['social_media_enable'] : false;
$phone_enable = array_key_exists('phone_enable', $headerConfig) ? $headerConfig['phone_enable'] : false;
$top_header_text = array_key_exists('top_header_text', $headerConfig) ? $headerConfig['top_header_text'] : false;
$language = array_key_exists('language', $headerConfig) ? $headerConfig['language'] : false;
$currency = array_key_exists('currency', $headerConfig) ? $headerConfig['currency'] : false;
$user_icon = array_key_exists('user', $font_icons) ? $font_icons['user'] : false;
$setting_icon = array_key_exists('setting', $font_icons) ? $font_icons['setting'] : false;
$whishlist_icon = array_key_exists('whishlist', $font_icons) ? $font_icons['whishlist'] : false;
$phone_icon = array_key_exists('contact', $font_icons) ? $font_icons['contact'] : false;
$search_icon = array_key_exists('search', $font_icons) ? $font_icons['search'] : false;
?>

<div class="search-drawer">
	<div class="container">
		<div class="title"><?php echo __('What are you looking for?') ;?></div>
		<?php echo $this->getChildHtml("topSearch"); ?>
		<span class="close icon" id="mbsearch-close"><svg xmlns="https://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span>
	</div>
</div>
<!-- Header Style-11 -->
<header class="page-header header-11">
	<!--Topbar Header-->
	<?php if($top_header): ?>
		<div class="top-header">
			<div class="container">
				<div class="d-flex align-item-center justify-space-between">
					<div class="flex-1 leftTop">
						<!--Social Top Header-->
						<?php if($social_media_enable): ?>
							<!-- Header Social Icon -->
							<div class="social-header">
								<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
							</div>
							<!-- End Header Social Icon -->
						<?php endif; ?>
						<!--End Social Top Header-->
					</div>

					<div class="flex-1 middleTop">
						<!--Top Links-->
						<div class="user-links panel header">
							<?php echo $this->getChildHtml("top.links"); ?>
						</div>
						<!--End Top Links-->

						<!--Free Shipping Msg-->
						<?php if($top_header_text): ?>
							<div class="shipping-msg">
								<?php 
								/* Get Number From String in which number start Like (%s)59 */
								preg_match_all('/\)[^\d]*(\d+(\.\d+)?)/', $top_header_text, $matches);
								if(isset($matches[1])&&(count($matches[1]) > 0))
								{
									$text_price = array();
									foreach($matches[1] as $key => $value):
									
										$convertedPrice = $poco_helper->getFreeShippingCurrentPrice($value,$storeId);
										$formattedPrice = $poco_helper->getFormattedPrice($convertedPrice);
										$text_price[$value] = $formattedPrice;
										$findString = '(%s)'.$value;
										$top_header_text =  str_replace($findString,$formattedPrice,$top_header_text);
										 
									endforeach;
								}
								?>
								<?php echo $top_header_text; ?>
							</div>
						<?php endif; ?>
						<!--End Free Shipping Msg-->
					</div>
					
					<div class="flex-1 rightTop">
						<!--Phone No-->
						<?php $contactNo = $poco_helper->getContactus('contact',$storeId);?>
						<?php if(($phone_enable)&&($contactNo)):?>
						<div class="phone-no">
							<a href="tel:<?php echo $contactNo; ?>">
								<span class="icon"><?= $phone_icon ?></span>
								<span class="number"><?php echo $contactNo; ?></span>
							</a>
						</div>
						<?php endif; ?>
						<!--End Phone No-->
					</div>
				</div>
			</div>
		</div>
    <?php endif; ?>
	<!--End Topbar Header-->

	<div class="container">
		<div id="header-content" class="header d-flex align-item-center justify-space-between">
			
			<!-- Mobile Navigation Bar -->
			<span data-action="toggle-nav" class="action nav-toggle">
				<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon bar_icon"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
				<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon close_icon"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
				<span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span>
			</span>
			<!-- End Mobile Navigation Bar -->

			<!-- Logo -->
			<div class="logo flex-1 col-2 pr-1 d-flex-small justify-content-center-small"><?php echo $this->getChildHtml("logo"); ?></div>
			<!-- End Logo -->

			 <!-- Main Navigation Menu -->
			<div class="main-nav flex-1 col-8">
				<?php echo $block->getChildHtml('navigation.sections'); ?>
			</div>
			<!-- End Main Navigation Menu -->
			
			<div class="icon-right flex-1 col-2 pl-1">
                <!-- Minicart Popup -->
				<div class="minicart">
					<?php echo $this->getChildHtml("minicart"); ?>
				</div>
				<!-- End Minicart Popup -->

				<!-- Wishlist Icon -->
				<div class="whilist-link" data-bind="scope: 'wishlist'">
					<a href="<?php /* @escapeNotVerified */ echo $this->getUrl('wishlist', ['_secure' => true]); ?>" aria-label="Wishlist"><span class="icon"><?= $whishlist_icon ?></span>
					<!-- ko if: wishlist().counter -->
					<span data-bind="text: wishlist().counter" class="wishlist-counter counter qty"></span>
					<!-- /ko -->
					</a>
				</div>
                <!-- End Wishlist Icon -->

                <!-- Setting Links -->
				<?php if(!$top_header): ?>
					<div class="setting-links">
						<div class="setting-icon">
							<span class="icon"><?= $user_icon ?></span>
						</div>
						<div class="setting-dropdown">
                            <!--Userlinks-->
							<div class="user-account links-cols">
								<div class="top-links">
									<?php echo $this->getChildHtml("top.links"); ?>
								</div>
							</div>
							<!-- End Userlinks -->
							<!-- Language Dropdown -->
							<?php if($language): ?>
								<?php if($poco_helper->isStoreMultiStoreView($storeId)): ?>
								<?php echo $this->getChildHtml("store_language_ver_2"); ?>
								<?php endif; ?>
							<?php endif; ?>
							<!-- End Language Dropdown -->
							<!-- Currency Dropdown -->
							<?php if($currency): ?>
								<?php if($poco_helper->isMultipleCurrency($storeId)): ?>
									<?php echo $this->getChildHtml("currency_ver_2"); ?>
								<?php endif; ?>
							<?php endif; ?>
							<!--Currency Dropdown-->
						</div>
					</div>
					<?php else: ?>
				<div class="setting-links stg_dd">
						<div class="setting-icon">
							<span class="icon"><?= $setting_icon ?></span>
						</div>
						<div class="setting-dropdown">
                            <!-- Language Dropdown -->
							<?php if($language): ?>
								<?php if($poco_helper->isStoreMultiStoreView($storeId)): ?>
								<?php echo $this->getChildHtml("store_language_ver_2"); ?>
								<?php endif; ?>
							<?php endif; ?>
							<!-- End Language Dropdown -->
							<!-- Currency Dropdown -->
							<?php if($currency): ?>
								<?php if($poco_helper->isMultipleCurrency($storeId)): ?>
									<?php echo $this->getChildHtml("currency_ver_2"); ?>
								<?php endif; ?>
							<?php endif; ?>
							<!--Currency Dropdown-->
						</div>
					</div>
				
				<?php endif; ?>
                <!--End Setting Links-->

				<!-- Search Bar -->
				<div class="search-toggle">
					<div class="topSearch f-right"><span class="icon"><?= $search_icon ?></span> <span class="label"><?php echo __('Search') ;?></span></div>
				</div>
				<!-- End Search Bar -->
			</div>
		</div>
	</div>
    
</header>
<!-- End Header Style-11 -->