<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magebees\PocoThemes\Block\Html\Header $block
 */
?>
<?php $poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data'); 
$storeId = $poco_helper->getStoreId();
$headerConfig =$poco_helper->getConfigGroup('header',$storeId);
$font_icons = $poco_helper->getConfigGroup('font_icons',$storeId);
$top_header = array_key_exists('top_header', $headerConfig) ? $headerConfig['top_header'] : false;
$social_media_enable = array_key_exists('social_media_enable', $headerConfig) ? $headerConfig['social_media_enable'] : false;
$phone_enable = array_key_exists('phone_enable', $headerConfig) ? $headerConfig['phone_enable'] : false;
$top_header_text = array_key_exists('top_header_text', $headerConfig) ? $headerConfig['top_header_text'] : false;
$language = array_key_exists('language', $headerConfig) ? $headerConfig['language'] : false;
$currency = array_key_exists('currency', $headerConfig) ? $headerConfig['currency'] : false;
$user_icon = array_key_exists('user', $font_icons) ? $font_icons['user'] : false;
$setting_icon = array_key_exists('setting', $font_icons) ? $font_icons['setting'] : false;
$whishlist_icon = array_key_exists('whishlist', $font_icons) ? $font_icons['whishlist'] : false;
$phone_icon = array_key_exists('contact', $font_icons) ? $font_icons['contact'] : false;
$search_icon = array_key_exists('search', $font_icons) ? $font_icons['search'] : false;
?>

<div class="search-drawer">
	<div class="container">
		<div class="title"><?php echo __('What are you looking for?') ;?></div>
		<?php  echo $this->getChildHtml("topSearch"); ?>
		<span class="close icon" id="mbsearch-close"><svg xmlns="https://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span>
	</div>
</div>
<!-- Header Style-7 -->
<header class="page-header header-7">
	<div class="container">
		<div id="header-content" class="header d-flex asc jcb">
			<div class="flex-1 col-3">
				<!-- Mobile Navigation Bar -->
				<span data-action="toggle-nav" class="action nav-toggle">
					<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon bar_icon"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
					<svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="st-icon close_icon"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
					<span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span>
				</span>
				<!-- End Mobile Navigation Bar -->
				<div class="search-toggle">
					<?php //echo $this->getChildHtml("topSearch"); ?>
					
					<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
												->setName('top.search.desktop')
												->setTemplate('Magebees_Ajaxsearch::form.mini.desktop.phtml')->toHtml(); 
					?>
					
					<a class="topSearch f-right" href="#;" title="<?php echo __('Search') ;?>"><span class="icon"><?= $search_icon ?></span></a>
				</div>
				<!-- End Search Bar -->
			</div>

			<!-- Logo -->
			<div class="logo flex-1 col-3 pr-1 pl-1 d-flex justify-content-center"><?php echo $this->getChildHtml("logo"); ?></div>
			<!-- End Logo -->
			
			<div class="icon-right flex-1 col-3 pl-1 d-flex jce asc">
                <!-- Setting Links -->
					<?php //if(!$top_header): ?>
						<div class="setting-links">
							<div class="setting-icon">
								<span class="icon"><?= $user_icon ?></span>
							</div>
							<div class="setting-dropdown">
								<!--Userlinks-->
								<div class="user-account links-cols">
									<div class="top-links">
										<h6 class="title body-font"><?php echo __('My Account') ;?></h6>
										<?php echo $this->getChildHtml("top.links"); ?>
									</div>
								</div>
								<!-- End Userlinks -->
								<!-- Language Dropdown -->
								 <?php if($language): ?>
								
									<?php if($poco_helper->isStoreMultiStoreView($storeId)): ?>
									<?php echo $this->getChildHtml("store_language_ver_2"); ?>
									<?php endif; ?>
								<?php endif; ?>
								<!-- End Language Dropdown -->
								<!-- Currency Dropdown -->
								 <?php if($currency): ?>
							
									<?php if($poco_helper->isMultipleCurrency($storeId)): ?>
										<?php echo $this->getChildHtml("currency_ver_2"); ?>
									<?php endif; ?>
								<?php endif; ?>
								<!--Currency Dropdown-->
							</div>
						</div>
					<?php //endif; ?>
					<!--End Setting Links-->
					
					<!-- Wishlist Icon -->
					<?php //if(!$top_header =$poco_helper->getHeader('top_header',$storeId)): ?>
						
						<div class="whilist-link" data-bind="scope: 'wishlist'">
							<a href="<?php /* @escapeNotVerified */ echo $this->getUrl('wishlist', ['_secure' => true]); ?>" title="<?php echo __('My Wishlist') ;?>" aria-label="Wishlist"><span class="icon"><?= $whishlist_icon ?></span>
								<!-- ko if: wishlist().counter -->
								<span data-bind="text: wishlist().counter" class="wishlist-counter counter qty"></span>
								<!-- /ko -->
							</a>
						</div>
					<?php //endif;?>

					 <!-- Minicart Popup -->
					<div class="minicart item">
						<?php echo $this->getChildHtml("minicart"); ?>
					</div>
					<!-- End Minicart Popup -->
			</div>
		</div>
	</div>

	<div class="container">
		<div class="d-flex asc jcb">
		 <?php if($top_header): ?>
			<div class="flex-1 d-flex alc jcs md_none top_left">
				<!--Social Top Header-->
				<?php if($social_media_enable): ?>
					<!-- Header Social Icon -->
					<div class="social-header">
						<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
					</div>
					<!-- End Header Social Icon -->
				<?php endif; ?>
				<!--End Social Top Header-->
			</div>
			<?php endif;?>

			<!-- Main Navigation Menu -->
			<?php if($top_header): ?>
				<div class="main-nav flex-1 d-flex alc jcc">
			<?php else: ?>
				<div class="main-nav">
			<?php endif;?>
				<div class="container">
					<?php echo $block->getChildHtml('navigation.sections'); ?>
				</div>
			</div>
			<!-- End Main Navigation Menu -->
			<?php if($top_header): ?>
			<div class="flex-1 d-flex alc jce md_none top_right">
				<!--Free Shipping Msg-->
				<?php if($top_header_text): ?>
					<div class="shipping-msg">
					<?php 
								/* Get Number From String in which number start Like (%s)59 */
								preg_match_all('/\)[^\d]*(\d+(\.\d+)?)/', $top_header_text, $matches);
								if(isset($matches[1])&&(count($matches[1]) > 0))
								{
									$text_price = array();
									foreach($matches[1] as $key => $value):
									
										$convertedPrice = $poco_helper->getFreeShippingCurrentPrice($value,$storeId);
										$formattedPrice = $poco_helper->getFormattedPrice($convertedPrice);
										$text_price[$value] = $formattedPrice;
										$findString = '(%s)'.$value;
										$top_header_text =  str_replace($findString,$formattedPrice,$top_header_text);
										 
									endforeach;
								}
								?>
						<?php echo $top_header_text; ?>
					</div>
				<?php endif; ?>
				<!--End Free Shipping Msg-->
				<?php $contactNo = $poco_helper->getContactus('contact',$storeId);?>
				<?php if(($phone_enable)&&($contactNo)):?>
							<div class="phone-no">
								<span class="lbl"><?= /* @escapeNotVerified */ __('Free call:') ?></span>
								<a href="tel:<?php echo $contactNo; ?>" title="<?php echo __('Contact No') ;?>">
									<span class="icon"><?= $phone_icon ?></span>
									<span class="number"><?php echo $contactNo; ?></span>
								</a>
							</div>
						<?php endif; ?>
			</div>
			<?php endif;?>
		</div>
	</div>
    
</header>
<!-- End Header Style-7 -->
