<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?>>
    <head <?= /* @noEscape */ $headAttributes ?>>
        <?= /* @noEscape */ $requireJs ?>
        <?= /* @noEscape */ $headContent ?>
        <?= /* @noEscape */ $headCritical ?>
        <?= /* @noEscape */ $headAssets ?>
        <?= /* @noEscape */ $headAdditional ?>
    </head>
	<?php 
	$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$_poco_helper = $_objectManager->get('Magebees\PocoThemes\Helper\Data');
	$loaderUrl = $_poco_helper->getLoadingIcon(); 
	?>
    <body data-container="body"
          data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?= /* @noEscape */ $loaderUrl ?>"}}'
        <?= /* @noEscape */ $bodyAttributes ?>>
        <?= /* @noEscape */ $layoutContent ?>
	</body>
	
</html>
