<?php 
$dialog_config=$this->getDialogConfig();
if(isset($dialog_config['livetime'])){
	$livetime=$dialog_config['livetime'];
} else {
	$livetime= 4;
}
$action=$this->identifyAction();
$CustomCartHelper = $this->helper('Magebees\CustomCartStyle\Helper\Data'); 
$show_add_to_cart_popup = 3;
?> 
<?php if ($CustomCartHelper->enableCustomCart()) : ?>
<?php $show_add_to_cart_popup = $CustomCartHelper->getMiniCartStyle(); ?>
<?php endif; ?> 
<script type="text/javascript">
    requirejs(['jquery','ajaxToCart'],
        function($) {
            $(document).ready(function() {
           	     $("body").on("click", function (e) {        
				    if (!$(e.target).closest('.cartDetails .action-close').length){
						$("#shopcontinue").trigger('click');
					}
				}); 
				$( "#loadingImage" ).insertBefore(".page-header");	
				var livetime=<?php echo $livetime ;?>;
                var show_popup=<?php echo $show_add_to_cart_popup ;?>;
					 $('body').on('click','.tocart',function(e){								
					var widget = $(this).ajaxToCart({});	
					/* POCO Theme Customization Start */
					if($('.mask-overlay').length >0 )
					{
						$('.mask-overlay').remove();
					}
					if($(".search-drawer").hasClass("search-drawer-open"))
					{
					$('.search-drawer').removeClass("search-drawer-open");	
					}
					/* POCO Theme Customization End */
					if ($(this).data('post')) {
						  var actionUrl = $(this).data('post').action;				
						  var params = $(this).data('post').data;
						  params.form_key = $('input[name=form_key]').val();		 
						  widget.ajaxToCart('ajaxSubmit',actionUrl,params,livetime,show_popup,$(this));
					}
					else
					{
						var form = $(this).closest('form');
						var productId = $(this).closest('li.product-item').find('div.price-box').data('product-id');					
							var url = $(this).closest('li.product-item').find('a.product-item-link').attr('href');
							var customurl=url+"?options=ajax";					
							if(customurl)
							{
								var params = form.serialize();
								if(params)
								{
									var actionUrl=form.attr('action');	
									var form_id = $(this).closest('form').attr('id');
									if(form_id)
									{
									 $('#'+form_id).mage('validation', {		
						            radioCheckboxClosest: '.nested',
						            submitHandler: function (form) {
						                var widget = $(form).ajaxToCart({
						                    bindSubmit: false
						                });
										document.getElementById('loadingImage').style['display']='block';
						                widget.ajaxToCart('ajaxSubmitForm', $(form),livetime,show_popup);
						                return false;
						           	 }
						        		});	
							        }	
							        else{
							        	widget.ajaxToCart('ajaxSubmit',actionUrl,params,livetime,show_popup,$(this));
							        }	
								}
								else
								{
									widget.ajaxToCart('ajaxPopup',customurl,livetime,show_popup);
								}													
							}				 
					}
					return false;
                });
				 $('body').on('click','.cart .action-delete',function(){
					var widget = $(this).ajaxToCart({});
					if ($(this).data('item')) 
					{
						 var actionUrl = $(this).data('item').action;				
						  var params = $(this).data('item').data;					
						  params.form_key = $('input[name=form_key]').val();						 
						  widget.ajaxToCart('ajaxSubmit',actionUrl,params,livetime,show_popup,$(this));
					}
				});
				 $('body').on('click','#shopcontinue',function(){
					var widget = $(this).ajaxToCart({});					 
					widget.ajaxToCart('shopContinue');
					});
            });
        });
</script>