<?php
/**
 * Copyright © 2018 Magebees, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* $block Magebees\CustomCartStyle\Block\MiniCart */
?>
<?php 
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data'); 
$store_Id = $poco_helper->getStoreId(); 
$freeShippingBarEnabled = $poco_helper->getThemeLayout('free_shipping_bar',$store_Id);
	?>
<div class="footer-minicart" id="poco-footer-minicart" data-block='minicartpro' style="display: none;">
	
    <div class="footer-cart-inner" data-bind="scope: 'minicartpro_content'">
        <a href="#;" class="cart-trigger" data-role="cart-trigger">
            <span class="flying-destination" data-role="flying-destination"></span>
            <span class="summary-count-label" data-role="cart-count">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->&nbsp;
                    <!-- ko i18n: 'items in your cart' --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('summary_count') -->
                    <!-- ko i18n: 'Your cart is empty' --><!-- /ko -->
                <!-- /ko -->
            </span>
            <span class="proccessing-label" data-role="cart-processing" style="display: none;">
                 <!-- ko i18n: 'Proccessing...' --><!-- /ko -->
            </span>
        </a>
        <div class="block-minicartpro" data-role="cart-content" style="display: none;">
            <?php if($freeShippingBarEnabled): ?>
				<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
					->setSection('footercart')
					->setTemplate("Magebees_PocoThemes::free_shipping_bar.phtml")->toHtml();?>
			<?php endif; ?>
	
			<div id="minicartpro-content-wrapper">
                <!-- ko template: 'Magebees_CustomCartStyle/minicart/content-footer.html' --><!-- /ko -->
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
	"[data-block='minicartpro']": {
		"Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
	}
}
</script>