<?php
/**
 * Copyright © 2018 Magebees, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* $block Magebees\CustomCartStyle\Block\MiniCart */
?>
<?php 
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data'); 
$store_Id = $poco_helper->getStoreId(); 
$freeShippingBarEnabled = $poco_helper->getThemeLayout('free_shipping_bar',$store_Id);
?>
<div class="minicart-popup" id="poco-minicart-popup" data-block='minicartpro' style="display:none;">
<?php if($freeShippingBarEnabled): ?>
				<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
					->setSection('cartpopup')
					->setTemplate("Magebees_PocoThemes::free_shipping_bar.phtml")->toHtml();?>
	<?php endif; ?>
    <div id="minicartpro-content-wrapper" class="minicartpro-content-wrapper" data-bind="scope: 'minicartpro_content'">
        <!-- ko template: 'Magebees_CustomCartStyle/minicart/content-popup.html' --><!-- /ko -->
    </div>
    <div class="ajaxcart-loader double-bounce-spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>

<script type="text/x-magento-init">
{
	"[data-block='minicartpro']": {
		"Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
	}
}
</script>