<?php use Magento\Framework\App\Action\Action; ?>
<?php 

/* POCO THEME CUSTOMIZATION ADD CODE Start */ 
include ($block->getTemplateFile('Magento_Catalog::product/product-list-theme-options.phtml'));
/* POCO THEME CUSTOMIZATION ADD CODE End */ 
	
	$bg_image = $poco_helper->getMediaUrl().$this->getData('wd_bgimage');

	$image_position = $this->getData('wd_position');

	if($image_position == "left"){

		$pos_class = "parallax-img-left";

		$content_class = "content-text-left";

		$text_class = "parallax-text-left";

	}elseif($image_position == "right"){

		$pos_class = "parallax-img-right";

		$content_class = "content-text-right";

		$text_class = "parallax-text-right";

	}else{

		$pos_class = "parallax-img-center";

		$content_class = "content-text-center";

		$text_class = "parallax-text-center";

	}

	$content_type = $this->getData('wd_content');

	$bg_color = $this->getData('wd_bgcolor');

	$title = $this->getData('wd_title');

	$subtitle = $this->getData('wd_subtitle');

	$description = $this->getData('wd_description');

	$shopnow_text = $this->getData('wd_shopnow_text');
	$products_per_row = $this->getData('wd_products_per_row');



	$spacing_class = '';
	$spacing_class .= $this->getData('wd_spacing')?'sections-spacing ':'';
	$spacing_class .= $this->getData('wd_bottom_spacing')?'section-bottom-spacing':'';
	$shopnow_url = $poco_helper->getUrl().$this->getData('wd_shopnow_url');
	$_productCollection = $block->getLoadedProductCollection();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<div class="parallax-section <?php echo $spacing_class ?>">
	<!-- Parallax Image -->
	<div class="half-col display-flex parallax-image <?php echo $pos_class ?>">
		<div class="zoom img_parallax" style="background-image: url('<?php echo $bg_image; ?>');"></div>
	</div>
	<!-- End Parallax Image -->

	<!-- Parallax Content -->
	<div class="half-col display-flex product-section feature-row__text parallax-img <?php echo $content_class; ?>"  style="background-image: url('<?php echo $bg_image; ?>'); background-color: <?php echo $bg_color ?>; background-repeat: no-repeat; background-attachment: fixed; background-position: center center;">
		<div class="parallax-product <?php echo $text_class ?>">
			<div class="feature-details container">
				<?php if ($content_type == "desc"): ?>
					<div class="section-title">
                        <?php if($title): ?>
						  <h2 class="title"><?php echo __($title) ?></h2>
                        <?php endif; ?>
                        <?php if($subtitle): ?>
				            <h3 class="section-subtitle"><?php echo __($subtitle) ?></h3>
                        <?php endif; ?>
                        <?php if($description): ?>
				            <p><?php echo $description ?></p>
                        <?php endif; ?>
                        <?php if($shopnow_text): ?>
				            <a href="<?php echo $shopnow_url ?>" class="btn button action primary"><span><?php echo __($shopnow_text) ?></span></a> 
                        <?php endif; ?>
					</div>
				<?php else: ?>
					<?php if (!$_productCollection->count()): ?>
						<div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
					<?php else: ?>
						<?php
							$viewMode = 'grid';
							$imageDisplayArea = 'category_page_grid';
							$showDescription = false;
							$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

							/**
							 * Position for actions regarding image size changing in vde if needed
							 */
						?>
						<div class="<?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
							<div class="section-title">
								<h2 class="title"><?php echo __($title) ?></h2>
								<h3 class="section-subtitle"><?php echo __($subtitle) ?></h3>
							</div>
							<?php $iterator = 1; ?>
							<ol class="products list items product-items <?php echo $btn_hover_effects_class; ?>">
							  <?php foreach ($_productCollection as $_product): ?>
									<?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
									<div class="product-item-info" data-container="product-grid">
										<div class="pro-hover">
											<div class="product-item-photo">
												<a href="<?php echo $_product->getProductUrl() ?>" tabindex="-1">
													<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template") ->setProduct($_product) ->setAspectRatio($aspect_ratio) ->setImageWidth($image_width) ->setImageHeight($image_height) ->setDisplayArea($imageDisplayArea) ->setTemplate("Magento_Catalog::product/image.phtml") ->toHtml();?>
												</a>
												<?php if(($show_deal_timer)&&(($hover_effects == 'button-hover-style7')||($hover_effects == 'button-hover-style11'))): ?>
													<!--Deal Timer On Hover Style7 Or 11 -->
													<?php echo $this->getLayout()->createBlock('Magebees\TodayDealProducts\Block\DealTimerListingProducts')->setProduct($_product) ->setTemplate('Magebees_TodayDealProducts::category_page_timer.phtml')->toHtml(); ?>
													<!--End Deal Timer On Hover Style7 Or 11 -->
												<?php endif; ?>
											</div>
											
											<?php if(($hover_effects != 'button-hover-style7')&&($hover_effects != 'button-hover-style11')): ?>
												<!--Buttons Hover Styles-->
												<?php echo $this->getLayout()->createBlock('Magebees\PocoThemes\Block\AddToButtons') ->setProduct($_product) ->setDisplayTimer($show_deal_timer) ->setShowCart($show_cart) ->setShowWishlist($show_wishlist) ->setShowCompare($show_compare) ->setShowAjaxQuickView($ajaxquickview_enable) ->setCurrentAction($currentAction) ->
							setAddCartIcon($add_cart_icon)->setWishlistIcon($whishlist_icon)->setCompareIcon($compare_icon)->setQuickviewIcon($quick_view_icon)->toHtml(); ?>
												
												<!--End Buttons Hover Styles-->
											<?php endif; ?>
										</div>

									   	<div class="product details product-item-details">
                                        	<div class="detail-left">
											<?php if($show_product_category): 
											echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
											->setProduct($_product)
											->setStoreId($storeId)
											->setTemplate
											("Magento_Catalog::product/category-link.phtml")
											->toHtml();
											endif; ?>
											<?php if($show_product_brand_name): ?>
                            
											<?php 
											echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
											->setProduct($_product)
											->setStoreId($storeId)
											->setBrandCode($brand_attribute_code)
											->setBrandUrlKey($brand_url_key)
											->setBaseUrl($webUrl)
											->setTemplate
											("Magento_Catalog::product/brand-link.phtml")
											->toHtml();
											?>
											<?php endif; ?>
											<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
											<strong class="product name product-item-name">
												<a class="product-item-link"
												   href="<?php echo $_product->getProductUrl() ?>">
													   <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
												</a>
											</strong>
											<?php if($show_product_rating): ?>
												<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
											<?php endif; ?>
											<?php if($show_product_sku): ?>
											<?php 
											echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
												->setProduct($_product)
												->setProductSkuLabel($product_sku_label)
												->setProductSkuSeparator($product_sku_separator)
												->setTemplate("Magento_Catalog::product/product-sku.phtml")
												->toHtml();?>
											<?php endif; ?>
											<?php if(($hover_effects != 'button-hover-style10')&&($show_product_price)): ?>      
												<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
											<?php endif; ?>
											<?php 
												if($buyNowEnabled):
													echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
													->setProduct($_product)
													->setButtonTitle($buyNowbuttonTitle)
													->setBuyNowListProduct($buyNowListProduct)
													->setTemplate("Magento_Catalog::product/buy-now.phtml")
													->toHtml();
												endif;
											?>
											
                                            <?php if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magebees_Swatches::product/listing/renderer.phtml"); ?>
												<!--Show Configurable Product Swatches -->
												<div class="swatches-listing">
													<?php echo $swatchBlock->setProduct($_product)->toHtml(); ?>
												</div>
												<!--End Configurable Product Swatches -->
                                            <?php } ?>
											<?php echo $block->getProductDetailsHtml($_product); ?>
                                            </div>
											<?php if((($hover_effects == 'button-hover-style10')||($hover_effects == 'button-hover-style12'))&&($allow_add_to_cart)): ?>
												<!-- Button Hover Style 10 Or 12 Start -->
												<div class="d-flex alc  <?php echo $bottom_btn_hover_effects_class; ?> hvr_dtl">
												
												<?php if(($hover_effects == 'button-hover-style10')&&($show_product_price)): ?> 
														<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
													<?php endif; ?>
													<div class="actions-primary">
														<?php if ($_product->isSaleable()): ?>
															<?php $postParams = $poco_helper->getAddToCartPostParams($_product); ?>
																<form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" method="post">
																	<input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
																	<input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
																	<?= $block->getBlockHtml('formkey') ?>
																	<?php $isHasOptions = $_product->getTypeInstance()->hasOptions($_product);?>
																	<?php if($isHasOptions): $add_to_cart_btn_title = 'Select Option'; endif; ?>
																	<button type="submit" title="<?= $escaper->escapeHtmlAttr(__($add_to_cart_btn_title)) ?>" class="action tocart primary" disabled>
																		<?php echo $add_cart_icon; ?>
																		<span><?= $escaper->escapeHtml(__($add_to_cart_btn_title)) ?></span>
																	</button>
																</form>
															<?php else: ?>
																<?php if ($_product->isAvailable()) :?>
																	<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
																<?php else :?>
																	<div class="stock unavailable"><span><?= $block->escapeHtml(__('Sold Out')) ?></span></div>
																<?php endif; ?>
														<?php endif; ?>
													</div>
												</div>	
												<!-- Button Hover Style 10 Or 12 End -->
											<?php endif; ?>

											<?php if(($hover_effects == 'button-hover-style7')||($hover_effects == 'button-hover-style11')): ?>
                                        		<!--Buttons Hover Styles 7 OR 11 -->
												<?php echo $this->getLayout()->createBlock('Magebees\PocoThemes\Block\AddToButtons') ->setProduct($_product)->setShowCart($show_cart) ->setShowWishlist($show_wishlist) ->setShowCompare($show_compare) ->setShowAjaxQuickView($ajaxquickview_enable) ->setCurrentAction($currentAction) ->
							setAddCartIcon($add_cart_icon)->setWishlistIcon($whishlist_icon)->setCompareIcon($compare_icon)->setQuickviewIcon($quick_view_icon)->toHtml(); ?>
												<!--End Buttons Hover Styles-->
											<?php endif; ?>
										</div>
									</div>
									<?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
								<?php endforeach; ?>
							</ol>
							<div class="view-more">
								<a href="<?php echo $shopnow_url ?>" class="action large-btn secondary"><span><?php echo __($shopnow_text) ?></span></a> 
							</div>
						</div>
						<?php if (!$block->isRedirectToCartEnabled()) : ?>
							<script type="text/x-magento-init">
								{
									"[data-role=tocart-form], .form.map.checkout": {
										"catalogAddToCart": {}
									}
								}
							</script>
						<?php endif; ?>
					<?php endif; ?>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<!-- End Parallax Content --> 
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "parallax": {}
        }
    }
</script>