<?php 
if($this->enableRelatedPost()):

if($this->_registry->registry('current_product')):
$product = $this->_registry->registry('current_product');
$product_id = $product->getId();
$postCollection = $this->getProductRelatedPosts($product_id);
$postCollection->getSelect()->orderRand();
$show_blog_tag = false;
	$show_blog_social_share = false;
	$show_blog_comment = false;
	$show_blog_author = false;
	
?>

	<?php  
		if(($postCollection->getSize())>0):
		$id = 'product-related-post-'.rand();
	?>
<div class="block mb-product-related-posts clearfix mb-post-grid-block">
	<div class="block-title title"><strong><?php echo $block->escapeHtml('Related Posts');?></strong></div>
	<ul id="<?php echo $id?>" class="items clearfix">
		<?php  
			$width = '417';
			$height = '303';
			$resize_type = null;
		if(!$width):
			$width = $block->imageWidth();
		endif;
		if(!$height):
			$height = $block->imageHeight();
		endif;
		if(!$resize_type):
			$resize_type = $block->imageResizeType();
		endif;
		foreach($postCollection as $_post):
			$_postUrl =  $block->getRelatedPosturl($_post);
			$_postName = $block->escapeHtml($_post->getTitle(), null, true);
			$featuredImageUrl = null;
			if($_post->getFeaturedImg()):
				$image_name = $_post->getFeaturedImg();
				$featuredImageUrl = $block->getFeaturedImageResize($image_name,$width,$height,$resize_type);
			endif;
		?>
		<li class="item" id="post-<?php echo $_post->getPostId();?>"> 
			<div class="mb-fetured-thumb"> 
				<a href="<?php echo $block->escapeHtml($_postUrl);?>" title="<?php echo $block->escapeHtml($_post->getTitle(), null, true);?>"> 
					<img loading="lazy" src="<?php echo $block->escapeHtml($featuredImageUrl);?>"  alt="<?php echo $block->escapeHtml($_post->getTitle(), null, true);?>">
				</a> 
			</div> 

			<h3 class="mb-post-title"><a href="<?php echo $block->escapeHtml($_postUrl);?>" title="<?php echo $block->escapeHtml($_post->getTitle(), null, true);?>">
					<?php echo $block->escapeHtml($_post->getTitle(), null, true);?>
				</a></h3> 

			<div class="mb-post-meta">	
				 

				<?php if ($_categoriesCount = $block->getCategoriesCount($_post)) { ?>
	            <div class="meta-item mb-post-categories">
	                <span class="label"><?php echo __('Categories:') ?></span>
					
					
					
					
					
					
					
	                <?php $cat_count = 0; 
	                    $post_cat_ids = $postCategoryIds = $_post->getCategoryIds();
	                        foreach($block->getBlockCategories($post_cat_ids) as $ct) { $cat_count++; ?>
					
					<?php if($cat_count > 2){ ?>	
	<a class="hide-cat-more" title="<?php echo $block->escapeHtml($ct['title']) ?>" href="<?php echo $ct['url']; ?>">
        <?php echo $block->escapeHtml($ct['title']) ?>
    <?php if ($cat_count != $_categoriesCount) { ?>, <?php } ?>
	</a>
	<?php }else{ ?>
	<a class="show-cat" title="<?php echo $block->escapeHtml($ct['title']) ?>" href="<?php echo $ct['url']; ?>">
         <?php echo $block->escapeHtml($ct['title']) ?>
    <?php if ($cat_count != $_categoriesCount) { ?>, <?php } ?>
	</a>
	
	<?php } ?>
					<?php } ?>
					<?php if($_categoriesCount > 2):?>
	<a class="show-more-cat showmorecat"><?php echo __(' More'); ?></a>
	<?php endif;?>
	            </div>
	            <?php } ?>
				<div class="meta-item mb-post-date">
					<span class="label"><?php echo __('Posted:') ?></span> <span class="value"><?php echo $block->getCreationDate($_post);?></span>
				</div>
				<?php 
				if(($block->getPostComment($_post)->getSize()) > 0) { ?>
			    <div class="meta-item mb-post-comments">
			        <span class="label"><?php echo __('Comments:') ?></span>
			        <a title="<?php echo $block->escapeHtml($_postName) ?>" href="<?php echo $_postUrl ?>#post-comments">
			            <?php echo $block->getPostComment($_post)->getSize(); ?>
			        </a>
			    </div>
			    <?php } ?> 
				<?php if($show_blog_tag):  ?>
				<?php 
				$_posttags = $block->getPostTags($_post);
				if ($_posttags->getSize()>0) { $_tagsTotalCount = $_posttags->getSize(); ?>
			    <div class="meta-item mb-post-tags">
			        <span class="label"><?php echo __('Tags:') ?></span>
			        <?php $tag_count = 0; foreach($_posttags as $tag) { $tag_count++; ?>
					<?php if($tag_count > 2){ ?>	
	<a class="hide-tag-more" title="<?php echo $block->escapeHtml($tag->getTitle()) ?>" href="<?php echo $block->getTagurl($tag); ?>">
        <?php echo $block->escapeHtml($tag->getTitle()) ?>
     <?php if ($tag_count != $_tagsTotalCount) { ?>, <?php } ?>
	</a>
	<?php }else{ ?>
	<a class="show-tag" title="<?php echo $block->escapeHtml($tag->getTitle()) ?>" href="<?php echo $block->getTagurl($tag); ?>">
        <?php echo $block->escapeHtml($tag->getTitle()) ?>
     <?php if ($tag_count != $_tagsTotalCount) { ?>, <?php } ?>
	</a>
	<?php } ?>
			        <?php } ?>
					<?php if($tag_count > 2):?>
	<a class="show-more-tag showmoretag"><?php echo __(' More'); ?></a>
	<?php endif;?>
			    </div>
		    	<?php }  ?>
<?php endif;?>
				<?php 
				if($show_blog_author):
					if ($_authorId = $_post->getAuthorId()) { 
					$authorInfo = $block->getPostAuthorInfo($_authorId);?>
			        <div class="meta-item post-author">
			            <span class="label"><?php echo __('Author:') ?></span>
			            <span class="value">
							<?php if($block->EnableAuthorLink()):?>
						    <a title="<?php echo $block->escapeHtml($authorInfo['name']) ?>" href="<?php echo $authorInfo['url']; ?>">
								<?php endif; ?>
						        <?php echo $block->escapeHtml($authorInfo['name']) ?>
						    <?php if($block->EnableAuthorLink()):?>
							</a>
							<?php endif; ?>
						</span>
			        </div>
	        	<?php } ?>
<?php endif;?>
<?php if($show_blog_social_share):	?>
				<div class="addthis_toolbox addthis_default_style meta-item"
	                addthis:url="<?php echo $_postUrl ?>"
	                addthis:title="<?php echo $_postName; ?>"
	                <?php if ($featuredImageUrl) { ?>
	                addthis:media="<?php echo $featuredImageUrl ?>"
	                <?php } ?>>
	                <a class="addthis_button_facebook"></a>
	                <a class="addthis_button_twitter"></a>
	                <a class="addthis_button_email"></a>
	                <a class="addthis_button_compact"></a>
	            </div>
				<?php endif;?>
	        </div>

        	<div class="clearfix mb-post-excerpt">
                <?php 
					$post_short_desc = $block->getPostShortContent($_post);
					$post_short_desc_length = 100;
				if (strlen($post_short_desc) > $post_short_desc_length) {
					  	$post_short_desc_cut = substr($post_short_desc, 0, $post_short_desc_length);
						$post_short_desc_cut_end = strrpos($post_short_desc_cut, ' ');
						$post_short_desc = $post_short_desc_cut_end? substr($post_short_desc_cut, 0, $post_short_desc_cut_end) : substr($post_short_desc_cut, 0);
						$post_short_desc .= '...'; 
						
					} else {
						$post_short_desc = $block->getPostShortContent($_post);
					}
						echo $block->getFormattedContent($post_short_desc);
				?>
	    	</div>
	    	<div class="mb-readmore">
	    		<a href="<?php echo $block->escapeHtml($_postUrl);?>" title="<?php echo $block->escapeHtml($_postName) ?>" class="mb-post-readmore action primary">
    				<?php echo __('Read more') ?>
    			</a>
    		</div>
    </li>
	
	<?php endforeach;	?>

<?php /* if($block->EnableAddThis()):?>
<script type="text/javascript">
if (window.addthis) {
                        addthis.toolbox('.addthis_toolbox');
                    }
	var addthis_config = {
        "ui_language": '<?php echo $block->getAddThisLanguage();?>',
        "data_track_clickback":false
    }
</script>
<script type="text/javascript" async src="//s7.addthis.com/js/250/addthis_widget.js#pubid=<?php echo $block->getAddThisId();?>"></script>
<?php endif;*/ ?>
		
</ul>
</div>

<?php
endif;
	endif;
endif;