<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$storeId = $poco_helper->getStoreId();	
$font_icons = $poco_helper->getConfigGroup('font_icons',$storeId);
$add_cart_icon = array_key_exists('add_cart', $font_icons) ? $font_icons['add_cart'] : false;
$themeLayoutConfig = $poco_helper->getConfigGroup('theme_layout',$storeId);
$show_cart = array_key_exists('add_to_cart', $themeLayoutConfig) ? $themeLayoutConfig['add_to_cart'] : false;
if($show_cart):
$block_quickview=$block->getLayout()->createBlock('\Magebees\Ajaxquickview\Block\QuickView');
$isAjaxaddtocartEnabled=$block_quickview->isAjaxaddtocartEnabled();
 $show_add_to_cart_popup = false;
if($isAjaxaddtocartEnabled)
{

$_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$store_id = $_helper->getStoreId();
$livetime = $_helper->getConfigValue('dialogboxsetting','livetime','ajaxaddtocart',$store_id);
$ajaxaddtocart_enable = $_helper->getConfigValue('setting','enable','ajaxaddtocart',$store_id);

$CustomCartHelper = $this->helper('Magebees\CustomCartStyle\Helper\Data'); 
$show_add_to_cart_popup = false;
if ($CustomCartHelper->enableCustomCart()) : 
$show_add_to_cart_popup = $CustomCartHelper->getMiniCartStyle(); 
endif;
}
?>
<?php

$quickview_popup_config=$block_quickview->getPopupConfig();
$_product = $block->getProduct(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()):
$QuantityValidators = $block->getQuantityValidators();

if(isset($QuantityValidators['validate-item-quantity']['qtyIncrements']))
{
$qtyIncrements = $QuantityValidators['validate-item-quantity']['qtyIncrements'];	
}else{
$qtyIncrements = 1;	
}
if(isset($QuantityValidators['validate-item-quantity']['minAllowed']))
{
$minAllowed = $QuantityValidators['validate-item-quantity']['minAllowed'];	
}else{
$minAllowed = 1;	
}
if(isset($QuantityValidators['validate-item-quantity']['maxAllowed']))
{
$maxAllowed = $QuantityValidators['validate-item-quantity']['maxAllowed'];	
}else{
$maxAllowed = 1000;	
}

 ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control control-qty-cart">
                <input type="number" name="qty" id="qty" maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty qty-qv"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                       <div class="qnty">
				            <div class="quantity-controls quantity-plus quantity-plus-qv"><i class="feather-plus icon"></i></div>
                            <div class="quantity-controls quantity-minus quantity-minus-qv"><i class="feather-minus icon"></i></div>
                        </div>
            </div>
                
			<script type="text/javascript">
						jQuery(document).ready(function($){
						var qtyIncrements = parseInt('<?php echo $qtyIncrements; ?>',10);	
						var minAllowed = parseInt('<?php echo $minAllowed; ?>',10);	
						var maxAllowed = parseInt('<?php echo $maxAllowed; ?>',10);	
						
							$('.quantity-plus-qv').click(function () {
								var currentQty = parseInt($('.qty-qv').val());
								var valueIncr = parseInt(currentQty+qtyIncrements);
								if(currentQty < maxAllowed){
									$('.qty-qv').val(valueIncr);
								}
								
							});
							
							$('.quantity-minus-qv').click(function () {
								
								var currentQty = parseInt($('.qty-qv').val());
								var valueDesc = parseInt(currentQty-qtyIncrements);
								if(currentQty > minAllowed){
									$('.qty-qv').val(valueDesc);
								}
								
							});
						});
					</script>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary ajaxproduct"
                    id="product-addtocart-button">
					<?php if($add_cart_icon): ?> <span class="icon"><?php echo $add_cart_icon;?></span><?php endif; ?>
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>

<?php elseif ($ajaxaddtocart_enable) : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magebees_Ajaxaddtocart/js/ajax-to-cart'
    ], function ($) {
        'use strict';

		var livetime=<?php echo $livetime ;?>;
		var show_popup=<?php echo $show_add_to_cart_popup ;?>;
           $('.product_addtocart_form_<?php echo $_product->getId(); ?>').mage('validation', {
			
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).ajaxToCart({
                    bindSubmit: false
                });
				document.getElementById('loadingImage').style['display']='block';
                widget.ajaxToCart('ajaxSubmitForm', $(form),livetime,show_popup);

                return false;
            }
        });
		$('body').on('click','#shopcontinue',function(){
					var widget = $(this).ajaxToCart({});					 
					widget.ajaxToCart('shopContinue');
					});
    });
</script>

<?php else : ?>

<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart',
		'Magento_Ui/js/modal/modal'
    ], function ($) {
        'use strict';

           $('.product_addtocart_form_<?php echo $_product->getId(); ?>').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));
				$('#product_quickview_content').modal('closeModal');
                return false;
            }
        });
    });
</script>
<?php endif; ?>
<?php endif; ?>