<?php
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magebees\AjaxCategoryProducts\Block\CategoryProducts
 */
?>


<?php
	$enable = $block->isEnabled();
	if($enable):
	
	$list_class = "";
	if($block->getListPosition()=="left"){
		$list_class = "left-sidebar";
	}
	
	$list_class_top = "";
	if($block->getListPosition()=="top"){
		$list_class_top = "full";
	}
	
	$_productCollection = $block->getLoadedProductCollection();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
	$number_of_products = $this->getData('wd_number_of_products');
?>

<div class="mage-ajaxpro-page <?php echo $list_class ?> <?php echo $list_class_top ?>">

    <div class="sidebar-shopby">
        <?php if($block->getShowCategorySectionTitle()):?>
		<div class="block-title">
           
                <strong role="heading" aria-level="2"><?php echo $block->getCategorySectionTitle() ?></strong>
            
        </div>
		<?php endif; ?>
        <div class="block-content">
            <ol id="cat-filter-<?php echo $block->getDefaultCategoryId() ?>" class="items category-filter">
                <?php foreach ($block->getConfigCategories() as $categoryId): ?>
                <?php $cat = $block->getCategoriesCollection($categoryId) ?>
                <li class="item">
                    <a href="javascript:void(0);" id="<?php echo $categoryId ?>">
                        <?php /* @escapeNotVerified */ echo $cat['name'] ?>
                    </a>
                </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
    
    <script type="text/javascript">
        requirejs(['jquery','ajaxloadcategory'], function($){
            var params = {'default_cat_id':'<?php echo $block->getDefaultCategoryId() ?>'};
            $('#cat-filter-<?php echo $block->getDefaultCategoryId() ?>').ajaxloadcategory(params);
        });	
    </script>
    
    <div id="category-product-id-<?php echo $block->getDefaultCategoryId() ?>" class="category-product-filter column main">
        <?php if (!count($_productCollection)): ?>
            <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
        <?php else: ?>
            <?php
           	    $viewMode = 'grid';
                $image = 'category_page_grid';
                $showDescription = false;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
           
    
            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
            $position = '';
            if ($pos != null) {
                $position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
                        . 'top:' . $block->getVar("{$image}:height") . 'px;"';
            }
            ?>
            
            <div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php // Product Image   ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <span style="width:240px;" class="product-image-container">
                                    <span style="padding-bottom: 137%;" class="product-image-wrapper">
                                        <?php
                                        $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                                ->init($_product, 'product_page_image_large')
                                                ->keepAspectRatio(TRUE)
                                                ->keepFrame(FALSE)
                                                ->resize(270, 371)
                                                ->getUrl();
                                        ?>
                                        <img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
                                    </span>
                                </span>
                            </a>
    
                            <div class="product details product-item-details">
                                <div style="padding: 0 2px;"><?php echo $block->getProductDetailsHtml($_product); ?></div>
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php echo $_product->getProductUrl() ?>">
                                           <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php echo $block->getProductPrice($_product) ?>
    
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo ($pos && strpos($pos, $viewMode . '-actions')) ? $position : ''; ?>>
                                        <div class="actions-primary"<?php echo ($pos && strpos($pos, $viewMode . '-primary')) ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo ($pos && strpos($pos, $viewMode . '-secondary')) ? $position : ''; ?>>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?php echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <span><?php echo __('Add to Compare') ?></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                    <?php endforeach; ?>
                </ol>
            </div>		
			<?php if($this->getSortBy() != 'random'): ?>
				<?php if ($block->getPagerHtml()): ?>
					<div id="category-products-pager-<?php echo $block->getDefaultCategoryId() ?>" class="toolbar toolbar-products"><?php echo $block->getPagerHtml(); ?></div>
				<?php endif ?>            <?php endif ?>
            
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
                    {
                        "[data-role=tocart-form], .form.map.checkout": {
                            "catalogAddToCart": {}
                        }
                    }
                </script>
            <?php endif; ?>			<?php if($this->getSortBy() != 'random'): ?>
				<?php if($this->total_collection > $number_of_products): ?>
					<div id="load-more-text-<?php echo $block->getDefaultCategoryId() ?>" class="load-more-text" >
						<a href="javascript:void(0);" id="load-more"><?php echo $block->getLoadMoreText() ?></a>
					</div>
					<div id="loading-text-<?php echo $block->getDefaultCategoryId() ?>" style="display:none" class="loading-text">
						<?php echo $block->getLoadingText() ?>
					</div>
				<?php endif; ?>			<?php endif; ?>
        <?php endif; ?>
    		<?php if($this->getSortBy() != 'random'): ?>
		<script>
            requirejs(['jquery','ajaxloadnext'], function($){
                var params = {'default_cat_id':'<?php echo $block->getDefaultCategoryId() ?>','donetext':'<p class="done-msg"><?php echo $block->getDoneText() ?></p>'};
                $('#category-product-id-<?php echo $block->getDefaultCategoryId() ?>').ajaxloadnext(params);
            });	
        </script>		<?php endif; ?>
    </div>

</div>
<?php endif; ?>