<?php 
	$randon_number = rand();	
	$res_div = '#bloglist'.$randon_number;
	$loading_div = '#loadingImage'.$randon_number;
	$url = $block->getUrl('blog/index/ajaxload');
	$poco_helper = $this->helper('Magebees\PocoThemes\Helper\Data');
$loaderUrl = $poco_helper->getLoadingIcon();  
?>
<div id="bloglist<?php echo $randon_number; ?>" class="ajx_loader">
<div id="loadingImage<?php echo $randon_number; ?>" style="display:none;"><div><img loading="lazy" src="<?php echo $loaderUrl; ?>" alt="Loading..." width="90" height="90" /></div></div>
</div>
<script type="text/javascript">
    require(['jquery'], function(jQuery){
        jQuery(document).ready(function() {
		
		jQuery.fn.isblogListingInViewport = function () {
			let elementTop = jQuery(this).offset().top;
			let elementBottom = elementTop + jQuery(this).outerHeight();
			let viewportTop = jQuery(window).scrollTop();
			let viewportBottom = viewportTop + jQuery(window).height();
			return elementBottom > viewportTop && elementTop < viewportBottom;
		};

jQuery(window).scroll(function () {
    if ((jQuery('<?= $res_div ?>').isblogListingInViewport())&&(!jQuery('<?= $res_div ?>').hasClass('ajax_send'))) {
        jQuery('<?= $res_div ?>').addClass('ajax_send');
        jQuery('<?= $loading_div ?>').show();
                jQuery.ajax({
                    context: '<?= $res_div ?>',
                    url: '<?= $url ?>',
                    type: "POST",
                    data: {'template': '<?= $this->template ?>','wd_spacing': '<?= $this->wd_spacing ?>','wd_bottom_spacing': '<?= $this->wd_bottom_spacing ?>','wd_show_heading': '<?= $this->wd_show_heading ?>','wd_heading': '<?= $this->wd_heading ?>','wd_show_description': '<?= $this->wd_show_description ?>','wd_description': '<?= $this->wd_description ?>','wd_post_show_feature_image': '<?= $this->wd_post_show_feature_image ?>','feature_image_height': '<?= $this->feature_image_height ?>','feature_image_width': '<?= $this->feature_image_width ?>',
'resize_type': '<?= $this->resize_type ?>','wd_post_type': '<?= $this->wd_post_type ?>','wd_post_limit': '<?= $this->wd_post_limit ?>','wd_slider': '<?= $this->wd_slider ?>','wd_items_per_slide': '<?= $this->wd_items_per_slide ?>','wd_autoscroll': '<?= $this->wd_autoscroll ?>','wd_auto_play_delaytime': '<?= $this->wd_auto_play_delaytime ?>','wd_autoplayoff': '<?= $this->wd_autoplayoff ?>','wd_slide_auto_height': '<?= $this->wd_slide_auto_height ?>','wd_navarrow': '<?= $this->wd_navarrow ?>',
'wd_pagination': '<?= $this->wd_pagination ?>','wd_infinite_loop': '<?= $this->wd_infinite_loop ?>','wd_scrollbar': '<?= $this->wd_scrollbar ?>','wd_grap_cursor': '<?= $this->wd_grap_cursor ?>','wd_sort_by': '<?= $this->wd_sort_by ?>','wd_category': '<?= $this->wd_category ?>','wd_comment_count': '<?= $this->wd_comment_count ?>','wd_tags': '<?= $this->wd_tags ?>','wd_author': '<?= $this->wd_author ?>','wd_add_this': '<?= $this->wd_add_this ?>','wd_post_readmore': '<?= $this->wd_post_readmore ?>','wd_post_show_view_all': '<?= $this->wd_post_show_view_all ?>','store_id': '<?= $this->store_id ?>','wd_bgimage': '<?= $this->wd_bgimage ?>','wd_bgcolor': '<?= $this->wd_bgcolor ?>','wd_items_per_row': '<?= $this->wd_items_per_row ?>','wd_post_content': '<?= $this->wd_post_content ?>','wd_post_view_all_text': '<?= $this->wd_post_view_all_text ?>','wd_post_show_view_all_url': '<?= $this->wd_post_show_view_all_url ?>','wd_post_ids': '<?= $this->wd_post_ids ?>'
					},
				}).done(function (data) {
					jQuery('<?= $loading_div ?>').hide();
					if(jQuery('<?= $res_div ?>').hasClass('ajx_loader'))
					{
						 jQuery('<?= $res_div ?>').removeClass('ajx_loader');
					}
                    jQuery('<?= $res_div ?>').html(data.result);
					 
                });
	} 
	});
	});
    });
</script>