<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $swatchData = $block->getSwatchData(); 
$helper=$this->helper('\Magebees\Layerednavigation\Helper\Data');
$multiselect_swatch=$block->isDefaultMultiselectSwatch();
$version=$helper->getMagentoVersion();
?>
<div class="swatch-attribute swatch-layered <?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>"
     attribute-code="<?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>" attribute-id="<?php /* @escapeNotVerified */ echo $swatchData['attribute_id'] ?>">
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as
		$option => $label): 
		
		$swatch_active=$block->isSwatchActive($option,$swatchData['attribute_code'] );
	 	if($multiselect_swatch==1){
				$multiselect_block=$block->getLayout()->createBlock('\Magebees\Layerednavigation\Block\Navigation\MultiSelect');
				$filterItem=$label['filterItem'];
				if($swatch_active)
				{
					$link_url=$multiselect_block->getFilterItemRemoveUrl($filterItem);
					$link_url=$block->escapeUrl($link_url);
				}
				else
				{
					$link_url=$multiselect_block->getFilterItemUrl($filterItem);
					$link_url=$block->escapeUrl($link_url);
				}					
				 }
		?>
            <a href="<?php if($multiselect_swatch==1){echo $link_url;}else{echo $block->escapeUrl($label['link']);} ?>" class="swatch-option-link-layered">
			
                <?php 
				if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="swatch-option <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                 data-option-type="3"
                                 data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 data-option-tooltip-thumb=""
                                 data-option-tooltip-value=""
                                ></div>
								
                            <?php    break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                            $swatchData['swatches'][$option]['value']); 
							$escapedUrl = $block->escapeUrl($swatchImagePath);
							
							?>
                            <div class="swatch-option image <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                 data-option-type="2"
                                 data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 data-option-tooltip-thumb="<?php /* @escapeNotVerified */ echo $swatchThumbPath ?>"
                                 data-option-tooltip-value=""
								 style="background: url(<?php /* @escapeNotVerified */ echo $swatchImagePath ?>) no-repeat center; background-size: initial;"
                                 ></div>
							<?php
                            $element = 'swatchImageOption' .$escaper->escapeJs($option);
                            $script = 'var ' .$element
                                .' = document.querySelector(\'div[data-option-id="' .$escaper->escapeJs($option)
                                .'"]\');' .PHP_EOL;
                            $script .= $element .'.style.background = "url(\''
                                .$escapedUrl .'\') no-repeat center";' .PHP_EOL;
                            $script .= $element .'.style.backgroundSize = "initial";';
                            ?>
                            <?= /* @noEscape*/ $secureRenderer->renderTag('script', [], $script, false); ?>
							
                            <?php    break;
                        case '1':
                            ?>
                            <div class="swatch-option color <?php if($swatch_active){?>selected <?php } echo $label['custom_style'] ?>"
                                 data-option-type="1"
                                 data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 data-option-tooltip-thumb=""
                                 data-option-tooltip-value="<?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?>"
                                 style="background: <?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?> no-repeat center; background-size: initial;"></div>
							<?php
                            $element = 'swatchImageOption' .$escaper->escapeJs($option);
                            $backgroundValue = $escaper->escapeJs(
                                str_replace('\'', '\\\'', $swatchData['swatches'][$option]['value'])
                            );
                            $script = 'var ' .$element
                                .' = document.querySelector(\'div[data-option-id="' .$escaper->escapeJs($option)
                                .'"]\');' .PHP_EOL;
                            $script .= $element .'.style.background = "' .$backgroundValue
                                .' no-repeat center";' .PHP_EOL;
                            $script .= $element .'.style.backgroundSize = "initial";';
                            ?>
                            <?= /* @noEscape*/ $secureRenderer->renderTag('script', [], $script, false); ?>
							
                            <?php    break;
                        case '0':
                        default:
						
                            ?>
                                <div class="swatch-option text <?php if($swatch_active){?>selected <?php } echo $label['custom_style'] ?>"
                                     data-option-type="0"
                                     data-option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                     data-option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                     data-option-tooltip-thumb=""
                                     data-option-tooltip-value=""
                                    ><?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?></div>
                            <?php    break;
                    } ?>
                <?php } ?>
				<div class="swacthesOptions">
					<span class="name-label"><?php /* @escapeNotVerified */ echo $label['label'] ?></span>
                    <span class="counter"><?php /* @escapeNotVerified */ echo $label['count'] ?></span>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
</div>
<?php $scriptString = <<<script

    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.{$block->escapeJs($swatchData['attribute_code'])}')
            .find('[data-option-type="1"], [data-option-type="2"], [data-option-type="0"], [data-option-type="3"]')
            .SwatchRendererTooltip();
    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script>
<?php if(version_compare($version, '2.1.0', '<'))
		{?>
			require(["jquery", "jquery/ui", "Magento_Swatches/js/SwatchRenderer"], function ($) {
		<?php }
		else
		{?>
			 require(["jquery", "jquery-ui-modules/core","jquery-ui-modules/widget", "Magento_Swatches/js/swatch-renderer"], function ($) {
	<?php }?>
   
        $('.swatch-layered.<?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
